// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deviceauth.sql

package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateProvisionalAuthorization = `-- name: ActivateProvisionalAuthorization :execrows
UPDATE deviceauth.device_authorizations
SET state='active', state_version=state_version+1, provisional_until=NULL, updated_at=$2
WHERE principal_id=$1 AND state='provisional' AND provisional_until >= $2
`

type ActivateProvisionalAuthorizationParams struct {
	PrincipalID uuid.UUID `json:"principal_id"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) ActivateProvisionalAuthorization(ctx context.Context, arg ActivateProvisionalAuthorizationParams) (int64, error) {
	result, err := q.db.Exec(ctx, activateProvisionalAuthorization, arg.PrincipalID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bindAccountSessionToAuthorization = `-- name: BindAccountSessionToAuthorization :execrows
UPDATE identity.account_sessions
SET device_authorization_id=$2, state_version=state_version+1, updated_at=$3
WHERE id=$1 AND state='active' AND device_authorization_id IS NULL
`

type BindAccountSessionToAuthorizationParams struct {
	ID                    uuid.UUID     `json:"id"`
	DeviceAuthorizationID uuid.NullUUID `json:"device_authorization_id"`
	UpdatedAt             time.Time     `json:"updated_at"`
}

func (q *Queries) BindAccountSessionToAuthorization(ctx context.Context, arg BindAccountSessionToAuthorizationParams) (int64, error) {
	result, err := q.db.Exec(ctx, bindAccountSessionToAuthorization, arg.ID, arg.DeviceAuthorizationID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const compromiseDeviceTokenFamily = `-- name: CompromiseDeviceTokenFamily :one
UPDATE deviceauth.device_token_families
SET state = 'compromised', state_version = state_version + 1, updated_at = $2
WHERE id = $1 AND state = 'active'
RETURNING id, authorization_id, state, state_version, access_token_hash, access_expires_at, idle_expires_at, absolute_expires_at, created_at, updated_at
`

type CompromiseDeviceTokenFamilyParams struct {
	ID        uuid.UUID `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CompromiseDeviceTokenFamily(ctx context.Context, arg CompromiseDeviceTokenFamilyParams) (DeviceauthDeviceTokenFamily, error) {
	row := q.db.QueryRow(ctx, compromiseDeviceTokenFamily, arg.ID, arg.UpdatedAt)
	var i DeviceauthDeviceTokenFamily
	err := row.Scan(
		&i.ID,
		&i.AuthorizationID,
		&i.State,
		&i.StateVersion,
		&i.AccessTokenHash,
		&i.AccessExpiresAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const consumeEnrollmentGrant = `-- name: ConsumeEnrollmentGrant :one
UPDATE deviceauth.enrollment_grants
SET state = 'consumed', consumed_at = $3, consumed_device_id = $2
WHERE token_hash = $1 AND state = 'unused' AND expires_at >= $3
RETURNING id, principal_id, account_session_id, token_hash, policy_marker, provisional_until, state, expires_at, created_at, consumed_at, consumed_device_id
`

type ConsumeEnrollmentGrantParams struct {
	TokenHash        []byte        `json:"token_hash"`
	ConsumedDeviceID uuid.NullUUID `json:"consumed_device_id"`
	ConsumedAt       sql.NullTime  `json:"consumed_at"`
}

func (q *Queries) ConsumeEnrollmentGrant(ctx context.Context, arg ConsumeEnrollmentGrantParams) (DeviceauthEnrollmentGrant, error) {
	row := q.db.QueryRow(ctx, consumeEnrollmentGrant, arg.TokenHash, arg.ConsumedDeviceID, arg.ConsumedAt)
	var i DeviceauthEnrollmentGrant
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.AccountSessionID,
		&i.TokenHash,
		&i.PolicyMarker,
		&i.ProvisionalUntil,
		&i.State,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ConsumedAt,
		&i.ConsumedDeviceID,
	)
	return i, err
}

const createDevice = `-- name: CreateDevice :exec
INSERT INTO deviceauth.devices
  (id, principal_id, display_name_ciphertext, display_name_key_version, signing_public_key, hpke_public_key, key_version, state, created_at, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,'active',$8,$8)
`

type CreateDeviceParams struct {
	ID                    uuid.UUID   `json:"id"`
	PrincipalID           uuid.UUID   `json:"principal_id"`
	DisplayNameCiphertext []byte      `json:"display_name_ciphertext"`
	DisplayNameKeyVersion pgtype.Int4 `json:"display_name_key_version"`
	SigningPublicKey      []byte      `json:"signing_public_key"`
	HpkePublicKey         []byte      `json:"hpke_public_key"`
	KeyVersion            int32       `json:"key_version"`
	CreatedAt             time.Time   `json:"created_at"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) error {
	_, err := q.db.Exec(ctx, createDevice,
		arg.ID,
		arg.PrincipalID,
		arg.DisplayNameCiphertext,
		arg.DisplayNameKeyVersion,
		arg.SigningPublicKey,
		arg.HpkePublicKey,
		arg.KeyVersion,
		arg.CreatedAt,
	)
	return err
}

const createDeviceAuthorization = `-- name: CreateDeviceAuthorization :exec
INSERT INTO deviceauth.device_authorizations
  (id, principal_id, device_id, state, state_version, provisional_until, created_at, updated_at)
VALUES ($1,$2,$3,$4,1,$5,$6,$6)
`

type CreateDeviceAuthorizationParams struct {
	ID               uuid.UUID    `json:"id"`
	PrincipalID      uuid.UUID    `json:"principal_id"`
	DeviceID         uuid.UUID    `json:"device_id"`
	State            string       `json:"state"`
	ProvisionalUntil sql.NullTime `json:"provisional_until"`
	CreatedAt        time.Time    `json:"created_at"`
}

func (q *Queries) CreateDeviceAuthorization(ctx context.Context, arg CreateDeviceAuthorizationParams) error {
	_, err := q.db.Exec(ctx, createDeviceAuthorization,
		arg.ID,
		arg.PrincipalID,
		arg.DeviceID,
		arg.State,
		arg.ProvisionalUntil,
		arg.CreatedAt,
	)
	return err
}

const createDevicePolicySnapshot = `-- name: CreateDevicePolicySnapshot :exec
INSERT INTO deviceauth.device_policy_snapshots
  (authorization_id, schema_version, policy, created_at)
VALUES ($1,'device-policy-v1',$2,$3)
`

type CreateDevicePolicySnapshotParams struct {
	AuthorizationID uuid.UUID       `json:"authorization_id"`
	Policy          json.RawMessage `json:"policy"`
	CreatedAt       time.Time       `json:"created_at"`
}

func (q *Queries) CreateDevicePolicySnapshot(ctx context.Context, arg CreateDevicePolicySnapshotParams) error {
	_, err := q.db.Exec(ctx, createDevicePolicySnapshot, arg.AuthorizationID, arg.Policy, arg.CreatedAt)
	return err
}

const createDeviceTokenFamily = `-- name: CreateDeviceTokenFamily :exec
INSERT INTO deviceauth.device_token_families
  (id, authorization_id, state, state_version, access_token_hash, access_expires_at,
   idle_expires_at, absolute_expires_at, created_at, updated_at)
VALUES ($1,$2,'active',1,$3,$4,$5,$6,$7,$7)
`

type CreateDeviceTokenFamilyParams struct {
	ID                uuid.UUID `json:"id"`
	AuthorizationID   uuid.UUID `json:"authorization_id"`
	AccessTokenHash   []byte    `json:"access_token_hash"`
	AccessExpiresAt   time.Time `json:"access_expires_at"`
	IdleExpiresAt     time.Time `json:"idle_expires_at"`
	AbsoluteExpiresAt time.Time `json:"absolute_expires_at"`
	CreatedAt         time.Time `json:"created_at"`
}

func (q *Queries) CreateDeviceTokenFamily(ctx context.Context, arg CreateDeviceTokenFamilyParams) error {
	_, err := q.db.Exec(ctx, createDeviceTokenFamily,
		arg.ID,
		arg.AuthorizationID,
		arg.AccessTokenHash,
		arg.AccessExpiresAt,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createEnrollmentGrant = `-- name: CreateEnrollmentGrant :exec
INSERT INTO deviceauth.enrollment_grants
  (id, principal_id, account_session_id, token_hash, policy_marker, provisional_until, state, expires_at, created_at)
VALUES ($1,$2,$3,$4,$5,$6,'unused',$7,$8)
`

type CreateEnrollmentGrantParams struct {
	ID               uuid.UUID    `json:"id"`
	PrincipalID      uuid.UUID    `json:"principal_id"`
	AccountSessionID uuid.UUID    `json:"account_session_id"`
	TokenHash        []byte       `json:"token_hash"`
	PolicyMarker     string       `json:"policy_marker"`
	ProvisionalUntil sql.NullTime `json:"provisional_until"`
	ExpiresAt        time.Time    `json:"expires_at"`
	CreatedAt        time.Time    `json:"created_at"`
}

func (q *Queries) CreateEnrollmentGrant(ctx context.Context, arg CreateEnrollmentGrantParams) error {
	_, err := q.db.Exec(ctx, createEnrollmentGrant,
		arg.ID,
		arg.PrincipalID,
		arg.AccountSessionID,
		arg.TokenHash,
		arg.PolicyMarker,
		arg.ProvisionalUntil,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const findDeviceAccessToken = `-- name: FindDeviceAccessToken :one
SELECT f.id AS family_id, f.authorization_id, f.state AS family_state,
       f.state_version AS family_state_version, f.access_expires_at,
       f.idle_expires_at, f.absolute_expires_at,
       a.principal_id, a.device_id, a.state AS authorization_state,
       a.state_version AS authorization_state_version,
       ac.state AS account_state
FROM deviceauth.device_token_families f
JOIN deviceauth.device_authorizations a ON a.id = f.authorization_id
JOIN identity.accounts ac ON ac.id = a.principal_id
WHERE f.access_token_hash = $1
`

type FindDeviceAccessTokenRow struct {
	FamilyID                  uuid.UUID `json:"family_id"`
	AuthorizationID           uuid.UUID `json:"authorization_id"`
	FamilyState               string    `json:"family_state"`
	FamilyStateVersion        int64     `json:"family_state_version"`
	AccessExpiresAt           time.Time `json:"access_expires_at"`
	IdleExpiresAt             time.Time `json:"idle_expires_at"`
	AbsoluteExpiresAt         time.Time `json:"absolute_expires_at"`
	PrincipalID               uuid.UUID `json:"principal_id"`
	DeviceID                  uuid.UUID `json:"device_id"`
	AuthorizationState        string    `json:"authorization_state"`
	AuthorizationStateVersion int64     `json:"authorization_state_version"`
	AccountState              string    `json:"account_state"`
}

func (q *Queries) FindDeviceAccessToken(ctx context.Context, accessTokenHash []byte) (FindDeviceAccessTokenRow, error) {
	row := q.db.QueryRow(ctx, findDeviceAccessToken, accessTokenHash)
	var i FindDeviceAccessTokenRow
	err := row.Scan(
		&i.FamilyID,
		&i.AuthorizationID,
		&i.FamilyState,
		&i.FamilyStateVersion,
		&i.AccessExpiresAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.PrincipalID,
		&i.DeviceID,
		&i.AuthorizationState,
		&i.AuthorizationStateVersion,
		&i.AccountState,
	)
	return i, err
}

const getActiveBundleAuthority = `-- name: GetActiveBundleAuthority :one
SELECT a.id AS authorization_id, a.principal_id, a.device_id,
       a.state AS authorization_state, a.state_version,
       d.hpke_public_key, d.key_version, p.schema_version, p.policy,
       ac.state AS account_state
FROM deviceauth.device_authorizations a
JOIN deviceauth.devices d ON d.id=a.device_id
JOIN deviceauth.device_policy_snapshots p ON p.authorization_id=a.id
JOIN identity.accounts ac ON ac.id=a.principal_id
WHERE a.id=$1 AND d.state='active'
  AND (a.state='active' OR (a.state='provisional' AND a.provisional_until >= $2))
`

type GetActiveBundleAuthorityParams struct {
	ID               uuid.UUID    `json:"id"`
	ProvisionalUntil sql.NullTime `json:"provisional_until"`
}

type GetActiveBundleAuthorityRow struct {
	AuthorizationID    uuid.UUID       `json:"authorization_id"`
	PrincipalID        uuid.UUID       `json:"principal_id"`
	DeviceID           uuid.UUID       `json:"device_id"`
	AuthorizationState string          `json:"authorization_state"`
	StateVersion       int64           `json:"state_version"`
	HpkePublicKey      []byte          `json:"hpke_public_key"`
	KeyVersion         int32           `json:"key_version"`
	SchemaVersion      string          `json:"schema_version"`
	Policy             json.RawMessage `json:"policy"`
	AccountState       string          `json:"account_state"`
}

func (q *Queries) GetActiveBundleAuthority(ctx context.Context, arg GetActiveBundleAuthorityParams) (GetActiveBundleAuthorityRow, error) {
	row := q.db.QueryRow(ctx, getActiveBundleAuthority, arg.ID, arg.ProvisionalUntil)
	var i GetActiveBundleAuthorityRow
	err := row.Scan(
		&i.AuthorizationID,
		&i.PrincipalID,
		&i.DeviceID,
		&i.AuthorizationState,
		&i.StateVersion,
		&i.HpkePublicKey,
		&i.KeyVersion,
		&i.SchemaVersion,
		&i.Policy,
		&i.AccountState,
	)
	return i, err
}

const getAuthorizationForUpdate = `-- name: GetAuthorizationForUpdate :one
SELECT id, principal_id, device_id, state, state_version, provisional_until, created_at, updated_at FROM deviceauth.device_authorizations WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetAuthorizationForUpdate(ctx context.Context, id uuid.UUID) (DeviceauthDeviceAuthorization, error) {
	row := q.db.QueryRow(ctx, getAuthorizationForUpdate, id)
	var i DeviceauthDeviceAuthorization
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.DeviceID,
		&i.State,
		&i.StateVersion,
		&i.ProvisionalUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceRefreshForUpdate = `-- name: GetDeviceRefreshForUpdate :one
SELECT r.token_hash, r.family_id, r.previous_token_hash, r.state AS refresh_state,
       r.issued_at, r.used_at, r.revoked_at,
       f.authorization_id, f.state AS family_state, f.state_version AS family_state_version,
       f.idle_expires_at, f.absolute_expires_at
FROM deviceauth.device_refresh_tokens r
JOIN deviceauth.device_token_families f ON f.id = r.family_id
WHERE r.token_hash = $1 FOR UPDATE OF r, f
`

type GetDeviceRefreshForUpdateRow struct {
	TokenHash          []byte       `json:"token_hash"`
	FamilyID           uuid.UUID    `json:"family_id"`
	PreviousTokenHash  []byte       `json:"previous_token_hash"`
	RefreshState       string       `json:"refresh_state"`
	IssuedAt           time.Time    `json:"issued_at"`
	UsedAt             sql.NullTime `json:"used_at"`
	RevokedAt          sql.NullTime `json:"revoked_at"`
	AuthorizationID    uuid.UUID    `json:"authorization_id"`
	FamilyState        string       `json:"family_state"`
	FamilyStateVersion int64        `json:"family_state_version"`
	IdleExpiresAt      time.Time    `json:"idle_expires_at"`
	AbsoluteExpiresAt  time.Time    `json:"absolute_expires_at"`
}

func (q *Queries) GetDeviceRefreshForUpdate(ctx context.Context, tokenHash []byte) (GetDeviceRefreshForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getDeviceRefreshForUpdate, tokenHash)
	var i GetDeviceRefreshForUpdateRow
	err := row.Scan(
		&i.TokenHash,
		&i.FamilyID,
		&i.PreviousTokenHash,
		&i.RefreshState,
		&i.IssuedAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.AuthorizationID,
		&i.FamilyState,
		&i.FamilyStateVersion,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
	)
	return i, err
}

const getGrantForChallenge = `-- name: GetGrantForChallenge :one
SELECT id, principal_id, account_session_id, token_hash, policy_marker, provisional_until, expires_at
FROM deviceauth.enrollment_grants
WHERE token_hash = $1 AND state = 'unused' AND expires_at >= $2
`

type GetGrantForChallengeParams struct {
	TokenHash []byte    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

type GetGrantForChallengeRow struct {
	ID               uuid.UUID    `json:"id"`
	PrincipalID      uuid.UUID    `json:"principal_id"`
	AccountSessionID uuid.UUID    `json:"account_session_id"`
	TokenHash        []byte       `json:"token_hash"`
	PolicyMarker     string       `json:"policy_marker"`
	ProvisionalUntil sql.NullTime `json:"provisional_until"`
	ExpiresAt        time.Time    `json:"expires_at"`
}

func (q *Queries) GetGrantForChallenge(ctx context.Context, arg GetGrantForChallengeParams) (GetGrantForChallengeRow, error) {
	row := q.db.QueryRow(ctx, getGrantForChallenge, arg.TokenHash, arg.ExpiresAt)
	var i GetGrantForChallengeRow
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.AccountSessionID,
		&i.TokenHash,
		&i.PolicyMarker,
		&i.ProvisionalUntil,
		&i.ExpiresAt,
	)
	return i, err
}

const insertDeviceRefreshToken = `-- name: InsertDeviceRefreshToken :exec
INSERT INTO deviceauth.device_refresh_tokens
  (token_hash, family_id, previous_token_hash, state, issued_at)
VALUES ($1,$2,$3,'active',$4)
`

type InsertDeviceRefreshTokenParams struct {
	TokenHash         []byte    `json:"token_hash"`
	FamilyID          uuid.UUID `json:"family_id"`
	PreviousTokenHash []byte    `json:"previous_token_hash"`
	IssuedAt          time.Time `json:"issued_at"`
}

func (q *Queries) InsertDeviceRefreshToken(ctx context.Context, arg InsertDeviceRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertDeviceRefreshToken,
		arg.TokenHash,
		arg.FamilyID,
		arg.PreviousTokenHash,
		arg.IssuedAt,
	)
	return err
}

const markDeviceRefreshUsed = `-- name: MarkDeviceRefreshUsed :one
UPDATE deviceauth.device_refresh_tokens
SET state='used', used_at=$2
WHERE token_hash=$1 AND state='active'
RETURNING token_hash, family_id, previous_token_hash, state, issued_at, used_at, revoked_at
`

type MarkDeviceRefreshUsedParams struct {
	TokenHash []byte       `json:"token_hash"`
	UsedAt    sql.NullTime `json:"used_at"`
}

func (q *Queries) MarkDeviceRefreshUsed(ctx context.Context, arg MarkDeviceRefreshUsedParams) (DeviceauthDeviceRefreshToken, error) {
	row := q.db.QueryRow(ctx, markDeviceRefreshUsed, arg.TokenHash, arg.UsedAt)
	var i DeviceauthDeviceRefreshToken
	err := row.Scan(
		&i.TokenHash,
		&i.FamilyID,
		&i.PreviousTokenHash,
		&i.State,
		&i.IssuedAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeDeviceAuthorization = `-- name: RevokeDeviceAuthorization :execrows
UPDATE deviceauth.device_authorizations
SET state='revoked', state_version=state_version+1, updated_at=$2
WHERE id=$1 AND state IN ('provisional','active','suspended')
`

type RevokeDeviceAuthorizationParams struct {
	ID        uuid.UUID `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) RevokeDeviceAuthorization(ctx context.Context, arg RevokeDeviceAuthorizationParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeDeviceAuthorization, arg.ID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeDeviceBoundAccountSessions = `-- name: RevokeDeviceBoundAccountSessions :execrows
UPDATE identity.account_sessions
SET state='revoked', state_version=state_version+1, updated_at=$2
WHERE device_authorization_id=$1 AND state IN ('active','review_required')
`

type RevokeDeviceBoundAccountSessionsParams struct {
	DeviceAuthorizationID uuid.NullUUID `json:"device_authorization_id"`
	UpdatedAt             time.Time     `json:"updated_at"`
}

func (q *Queries) RevokeDeviceBoundAccountSessions(ctx context.Context, arg RevokeDeviceBoundAccountSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeDeviceBoundAccountSessions, arg.DeviceAuthorizationID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeDeviceRecord = `-- name: RevokeDeviceRecord :execrows
UPDATE deviceauth.devices
SET state='revoked', updated_at=$2
WHERE id=$1 AND state IN ('active','suspended')
`

type RevokeDeviceRecordParams struct {
	ID        uuid.UUID `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) RevokeDeviceRecord(ctx context.Context, arg RevokeDeviceRecordParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeDeviceRecord, arg.ID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeDeviceRefreshTokens = `-- name: RevokeDeviceRefreshTokens :execrows
UPDATE deviceauth.device_refresh_tokens
SET state='revoked', revoked_at=$2
WHERE family_id=$1 AND state='active'
`

type RevokeDeviceRefreshTokensParams struct {
	FamilyID  uuid.UUID    `json:"family_id"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

func (q *Queries) RevokeDeviceRefreshTokens(ctx context.Context, arg RevokeDeviceRefreshTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeDeviceRefreshTokens, arg.FamilyID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateDeviceFamilyAccess = `-- name: RotateDeviceFamilyAccess :one
UPDATE deviceauth.device_token_families
SET access_token_hash=$2, access_expires_at=$3, idle_expires_at=$4,
    state_version=state_version+1, updated_at=$5
WHERE id=$1 AND state='active' AND idle_expires_at >= $5 AND absolute_expires_at >= $5
RETURNING id, authorization_id, state, state_version, access_token_hash, access_expires_at, idle_expires_at, absolute_expires_at, created_at, updated_at
`

type RotateDeviceFamilyAccessParams struct {
	ID              uuid.UUID `json:"id"`
	AccessTokenHash []byte    `json:"access_token_hash"`
	AccessExpiresAt time.Time `json:"access_expires_at"`
	IdleExpiresAt   time.Time `json:"idle_expires_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) RotateDeviceFamilyAccess(ctx context.Context, arg RotateDeviceFamilyAccessParams) (DeviceauthDeviceTokenFamily, error) {
	row := q.db.QueryRow(ctx, rotateDeviceFamilyAccess,
		arg.ID,
		arg.AccessTokenHash,
		arg.AccessExpiresAt,
		arg.IdleExpiresAt,
		arg.UpdatedAt,
	)
	var i DeviceauthDeviceTokenFamily
	err := row.Scan(
		&i.ID,
		&i.AuthorizationID,
		&i.State,
		&i.StateVersion,
		&i.AccessTokenHash,
		&i.AccessExpiresAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
