// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeIdempotency = `-- name: CompleteIdempotency :one
UPDATE idempotency_records
SET state = 'completed', response_status = $5, response_ciphertext = $6, response_key_version=$7
WHERE principal_scope = $1 AND operation = $2 AND idempotency_key_hash = $3
  AND request_digest=$4 AND state = 'in_progress'
RETURNING principal_scope, operation, idempotency_key_hash, request_digest, state, response_status, response_ciphertext, response_key_version, created_at, expires_at
`

type CompleteIdempotencyParams struct {
	PrincipalScope     string      `json:"principal_scope"`
	Operation          string      `json:"operation"`
	IdempotencyKeyHash []byte      `json:"idempotency_key_hash"`
	RequestDigest      []byte      `json:"request_digest"`
	ResponseStatus     pgtype.Int4 `json:"response_status"`
	ResponseCiphertext []byte      `json:"response_ciphertext"`
	ResponseKeyVersion pgtype.Int4 `json:"response_key_version"`
}

func (q *Queries) CompleteIdempotency(ctx context.Context, arg CompleteIdempotencyParams) (IdempotencyRecord, error) {
	row := q.db.QueryRow(ctx, completeIdempotency,
		arg.PrincipalScope,
		arg.Operation,
		arg.IdempotencyKeyHash,
		arg.RequestDigest,
		arg.ResponseStatus,
		arg.ResponseCiphertext,
		arg.ResponseKeyVersion,
	)
	var i IdempotencyRecord
	err := row.Scan(
		&i.PrincipalScope,
		&i.Operation,
		&i.IdempotencyKeyHash,
		&i.RequestDigest,
		&i.State,
		&i.ResponseStatus,
		&i.ResponseCiphertext,
		&i.ResponseKeyVersion,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getIdempotencyForUpdate = `-- name: GetIdempotencyForUpdate :one
SELECT principal_scope, operation, idempotency_key_hash, request_digest, state, response_status, response_ciphertext, response_key_version, created_at, expires_at FROM idempotency_records
WHERE principal_scope=$1 AND operation=$2 AND idempotency_key_hash=$3
FOR UPDATE
`

type GetIdempotencyForUpdateParams struct {
	PrincipalScope     string `json:"principal_scope"`
	Operation          string `json:"operation"`
	IdempotencyKeyHash []byte `json:"idempotency_key_hash"`
}

func (q *Queries) GetIdempotencyForUpdate(ctx context.Context, arg GetIdempotencyForUpdateParams) (IdempotencyRecord, error) {
	row := q.db.QueryRow(ctx, getIdempotencyForUpdate, arg.PrincipalScope, arg.Operation, arg.IdempotencyKeyHash)
	var i IdempotencyRecord
	err := row.Scan(
		&i.PrincipalScope,
		&i.Operation,
		&i.IdempotencyKeyHash,
		&i.RequestDigest,
		&i.State,
		&i.ResponseStatus,
		&i.ResponseCiphertext,
		&i.ResponseKeyVersion,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const pruneIdempotencyRecords = `-- name: PruneIdempotencyRecords :execrows
DELETE FROM idempotency_records WHERE expires_at < $1 AND state IN ('completed','failed')
`

func (q *Queries) PruneIdempotencyRecords(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, pruneIdempotencyRecords, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tryBeginIdempotency = `-- name: TryBeginIdempotency :execrows
INSERT INTO idempotency_records
  (principal_scope, operation, idempotency_key_hash, request_digest, state, created_at, expires_at)
VALUES ($1,$2,$3,$4,'in_progress',$5,$6)
ON CONFLICT (principal_scope, operation, idempotency_key_hash) DO NOTHING
`

type TryBeginIdempotencyParams struct {
	PrincipalScope     string    `json:"principal_scope"`
	Operation          string    `json:"operation"`
	IdempotencyKeyHash []byte    `json:"idempotency_key_hash"`
	RequestDigest      []byte    `json:"request_digest"`
	CreatedAt          time.Time `json:"created_at"`
	ExpiresAt          time.Time `json:"expires_at"`
}

func (q *Queries) TryBeginIdempotency(ctx context.Context, arg TryBeginIdempotencyParams) (int64, error) {
	result, err := q.db.Exec(ctx, tryBeginIdempotency,
		arg.PrincipalScope,
		arg.Operation,
		arg.IdempotencyKeyHash,
		arg.RequestDigest,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
