// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package store

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptTOTPStep = `-- name: AcceptTOTPStep :execrows
UPDATE identity.totp_credentials
SET last_accepted_step = $2
WHERE principal_id = $1 AND state = 'active'
  AND (last_accepted_step IS NULL OR last_accepted_step < $2)
`

type AcceptTOTPStepParams struct {
	PrincipalID      uuid.UUID   `json:"principal_id"`
	LastAcceptedStep pgtype.Int8 `json:"last_accepted_step"`
}

func (q *Queries) AcceptTOTPStep(ctx context.Context, arg AcceptTOTPStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptTOTPStep, arg.PrincipalID, arg.LastAcceptedStep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const activateTOTP = `-- name: ActivateTOTP :execrows
UPDATE identity.totp_credentials
SET state='active', last_accepted_step=$2, verified_at=$3
WHERE principal_id=$1 AND state='pending'
`

type ActivateTOTPParams struct {
	PrincipalID      uuid.UUID    `json:"principal_id"`
	LastAcceptedStep pgtype.Int8  `json:"last_accepted_step"`
	VerifiedAt       sql.NullTime `json:"verified_at"`
}

func (q *Queries) ActivateTOTP(ctx context.Context, arg ActivateTOTPParams) (int64, error) {
	result, err := q.db.Exec(ctx, activateTOTP, arg.PrincipalID, arg.LastAcceptedStep, arg.VerifiedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const activateVerifiedAccount = `-- name: ActivateVerifiedAccount :one
UPDATE identity.accounts
SET state = 'active', state_version = state_version + 1, updated_at = $2
WHERE id = $1 AND state = 'pending_email'
RETURNING id, state, state_version, locale, created_at, updated_at
`

type ActivateVerifiedAccountParams struct {
	ID        uuid.UUID `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ActivateVerifiedAccount(ctx context.Context, arg ActivateVerifiedAccountParams) (IdentityAccount, error) {
	row := q.db.QueryRow(ctx, activateVerifiedAccount, arg.ID, arg.UpdatedAt)
	var i IdentityAccount
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.StateVersion,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearPendingEmailDelivery = `-- name: ClearPendingEmailDelivery :execrows
UPDATE identity.email_identities
SET verification_delivery_id=NULL, verification_delivery_ciphertext=NULL,
    verification_delivery_key_version=NULL, updated_at=$2
WHERE verification_delivery_id=$1
`

type ClearPendingEmailDeliveryParams struct {
	VerificationDeliveryID uuid.NullUUID `json:"verification_delivery_id"`
	UpdatedAt              time.Time     `json:"updated_at"`
}

func (q *Queries) ClearPendingEmailDelivery(ctx context.Context, arg ClearPendingEmailDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearPendingEmailDelivery, arg.VerificationDeliveryID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeEmailVerification = `-- name: ConsumeEmailVerification :one
UPDATE identity.email_identities
SET verification_consumed_at = $3, verified_at = $3, updated_at = $3
WHERE principal_id = $1
  AND verification_token_hash = $2
  AND verification_consumed_at IS NULL
  AND verification_expires_at >= $3
RETURNING id, principal_id, lookup_key_version, lookup_digest, ciphertext, encryption_key_version, verification_token_hash, verification_expires_at, verification_consumed_at, verification_delivery_id, verification_delivery_ciphertext, verification_delivery_key_version, verified_at, created_at, updated_at
`

type ConsumeEmailVerificationParams struct {
	PrincipalID            uuid.UUID    `json:"principal_id"`
	VerificationTokenHash  []byte       `json:"verification_token_hash"`
	VerificationConsumedAt sql.NullTime `json:"verification_consumed_at"`
}

func (q *Queries) ConsumeEmailVerification(ctx context.Context, arg ConsumeEmailVerificationParams) (IdentityEmailIdentity, error) {
	row := q.db.QueryRow(ctx, consumeEmailVerification, arg.PrincipalID, arg.VerificationTokenHash, arg.VerificationConsumedAt)
	var i IdentityEmailIdentity
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.LookupKeyVersion,
		&i.LookupDigest,
		&i.Ciphertext,
		&i.EncryptionKeyVersion,
		&i.VerificationTokenHash,
		&i.VerificationExpiresAt,
		&i.VerificationConsumedAt,
		&i.VerificationDeliveryID,
		&i.VerificationDeliveryCiphertext,
		&i.VerificationDeliveryKeyVersion,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const consumePasswordReset = `-- name: ConsumePasswordReset :one
UPDATE identity.password_credentials
SET policy_version=$3, memory_kib=$4, time_cost=$5, parallelism=$6,
    salt=$7, password_hash=$8, reset_consumed_at=$9,
    reset_delivery_id=NULL, reset_delivery_ciphertext=NULL,
    reset_delivery_key_version=NULL, updated_at=$9
WHERE principal_id=$1 AND reset_token_hash=$2
  AND reset_consumed_at IS NULL AND reset_expires_at >= $9
RETURNING principal_id, policy_version, memory_kib, time_cost, parallelism, salt, password_hash, reset_token_hash, reset_expires_at, reset_consumed_at, reset_delivery_id, reset_delivery_ciphertext, reset_delivery_key_version, updated_at
`

type ConsumePasswordResetParams struct {
	PrincipalID     uuid.UUID    `json:"principal_id"`
	ResetTokenHash  []byte       `json:"reset_token_hash"`
	PolicyVersion   int32        `json:"policy_version"`
	MemoryKib       int32        `json:"memory_kib"`
	TimeCost        int32        `json:"time_cost"`
	Parallelism     int32        `json:"parallelism"`
	Salt            []byte       `json:"salt"`
	PasswordHash    []byte       `json:"password_hash"`
	ResetConsumedAt sql.NullTime `json:"reset_consumed_at"`
}

func (q *Queries) ConsumePasswordReset(ctx context.Context, arg ConsumePasswordResetParams) (IdentityPasswordCredential, error) {
	row := q.db.QueryRow(ctx, consumePasswordReset,
		arg.PrincipalID,
		arg.ResetTokenHash,
		arg.PolicyVersion,
		arg.MemoryKib,
		arg.TimeCost,
		arg.Parallelism,
		arg.Salt,
		arg.PasswordHash,
		arg.ResetConsumedAt,
	)
	var i IdentityPasswordCredential
	err := row.Scan(
		&i.PrincipalID,
		&i.PolicyVersion,
		&i.MemoryKib,
		&i.TimeCost,
		&i.Parallelism,
		&i.Salt,
		&i.PasswordHash,
		&i.ResetTokenHash,
		&i.ResetExpiresAt,
		&i.ResetConsumedAt,
		&i.ResetDeliveryID,
		&i.ResetDeliveryCiphertext,
		&i.ResetDeliveryKeyVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const consumeRecoveryCode = `-- name: ConsumeRecoveryCode :one
UPDATE identity.recovery_code_sets
SET code_hashes=array_remove(code_hashes, $2::bytea),
    state=CASE WHEN cardinality(array_remove(code_hashes, $2::bytea))=0 THEN 'exhausted' ELSE state END,
    updated_at=$3
WHERE id=$1 AND state='active' AND $2::bytea=ANY(code_hashes)
RETURNING id, principal_id, generation, code_hashes, state, created_at, updated_at
`

type ConsumeRecoveryCodeParams struct {
	ID        uuid.UUID `json:"id"`
	Column2   []byte    `json:"column_2"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) (IdentityRecoveryCodeSet, error) {
	row := q.db.QueryRow(ctx, consumeRecoveryCode, arg.ID, arg.Column2, arg.UpdatedAt)
	var i IdentityRecoveryCodeSet
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.Generation,
		&i.CodeHashes,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAccount = `-- name: CreateAccount :exec
INSERT INTO identity.accounts (id, state, state_version, locale, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAccountParams struct {
	ID           uuid.UUID `json:"id"`
	State        string    `json:"state"`
	StateVersion int64     `json:"state_version"`
	Locale       string    `json:"locale"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.Exec(ctx, createAccount,
		arg.ID,
		arg.State,
		arg.StateVersion,
		arg.Locale,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createAccountSession = `-- name: CreateAccountSession :exec
INSERT INTO identity.account_sessions
  (id, principal_id, state, state_version, client_signing_public_key, access_token_hash,
   access_expires_at, absolute_expires_at, created_at, updated_at)
VALUES ($1, $2, 'active', 1, $3, $4, $5, $6, $7, $7)
`

type CreateAccountSessionParams struct {
	ID                     uuid.UUID `json:"id"`
	PrincipalID            uuid.UUID `json:"principal_id"`
	ClientSigningPublicKey []byte    `json:"client_signing_public_key"`
	AccessTokenHash        []byte    `json:"access_token_hash"`
	AccessExpiresAt        time.Time `json:"access_expires_at"`
	AbsoluteExpiresAt      time.Time `json:"absolute_expires_at"`
	CreatedAt              time.Time `json:"created_at"`
}

func (q *Queries) CreateAccountSession(ctx context.Context, arg CreateAccountSessionParams) error {
	_, err := q.db.Exec(ctx, createAccountSession,
		arg.ID,
		arg.PrincipalID,
		arg.ClientSigningPublicKey,
		arg.AccessTokenHash,
		arg.AccessExpiresAt,
		arg.AbsoluteExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createEmailIdentity = `-- name: CreateEmailIdentity :exec
INSERT INTO identity.email_identities
  (id, principal_id, lookup_key_version, lookup_digest, ciphertext, encryption_key_version,
   verification_token_hash, verification_expires_at, verification_delivery_id,
   verification_delivery_ciphertext, verification_delivery_key_version, created_at, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$12)
`

type CreateEmailIdentityParams struct {
	ID                             uuid.UUID     `json:"id"`
	PrincipalID                    uuid.UUID     `json:"principal_id"`
	LookupKeyVersion               int32         `json:"lookup_key_version"`
	LookupDigest                   []byte        `json:"lookup_digest"`
	Ciphertext                     []byte        `json:"ciphertext"`
	EncryptionKeyVersion           int32         `json:"encryption_key_version"`
	VerificationTokenHash          []byte        `json:"verification_token_hash"`
	VerificationExpiresAt          sql.NullTime  `json:"verification_expires_at"`
	VerificationDeliveryID         uuid.NullUUID `json:"verification_delivery_id"`
	VerificationDeliveryCiphertext []byte        `json:"verification_delivery_ciphertext"`
	VerificationDeliveryKeyVersion pgtype.Int4   `json:"verification_delivery_key_version"`
	CreatedAt                      time.Time     `json:"created_at"`
}

func (q *Queries) CreateEmailIdentity(ctx context.Context, arg CreateEmailIdentityParams) error {
	_, err := q.db.Exec(ctx, createEmailIdentity,
		arg.ID,
		arg.PrincipalID,
		arg.LookupKeyVersion,
		arg.LookupDigest,
		arg.Ciphertext,
		arg.EncryptionKeyVersion,
		arg.VerificationTokenHash,
		arg.VerificationExpiresAt,
		arg.VerificationDeliveryID,
		arg.VerificationDeliveryCiphertext,
		arg.VerificationDeliveryKeyVersion,
		arg.CreatedAt,
	)
	return err
}

const createPasskeyCredential = `-- name: CreatePasskeyCredential :exec
INSERT INTO identity.passkey_credentials
  (credential_id, principal_id, public_key, attestation_format, transports,
   protocol_flags, sign_count, state, created_at, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,'active',$8,$8)
`

type CreatePasskeyCredentialParams struct {
	CredentialID      []byte    `json:"credential_id"`
	PrincipalID       uuid.UUID `json:"principal_id"`
	PublicKey         []byte    `json:"public_key"`
	AttestationFormat string    `json:"attestation_format"`
	Transports        []string  `json:"transports"`
	ProtocolFlags     int16     `json:"protocol_flags"`
	SignCount         int64     `json:"sign_count"`
	CreatedAt         time.Time `json:"created_at"`
}

func (q *Queries) CreatePasskeyCredential(ctx context.Context, arg CreatePasskeyCredentialParams) error {
	_, err := q.db.Exec(ctx, createPasskeyCredential,
		arg.CredentialID,
		arg.PrincipalID,
		arg.PublicKey,
		arg.AttestationFormat,
		arg.Transports,
		arg.ProtocolFlags,
		arg.SignCount,
		arg.CreatedAt,
	)
	return err
}

const createPasswordCredential = `-- name: CreatePasswordCredential :exec
INSERT INTO identity.password_credentials
  (principal_id, policy_version, memory_kib, time_cost, parallelism, salt, password_hash, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
`

type CreatePasswordCredentialParams struct {
	PrincipalID   uuid.UUID `json:"principal_id"`
	PolicyVersion int32     `json:"policy_version"`
	MemoryKib     int32     `json:"memory_kib"`
	TimeCost      int32     `json:"time_cost"`
	Parallelism   int32     `json:"parallelism"`
	Salt          []byte    `json:"salt"`
	PasswordHash  []byte    `json:"password_hash"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) CreatePasswordCredential(ctx context.Context, arg CreatePasswordCredentialParams) error {
	_, err := q.db.Exec(ctx, createPasswordCredential,
		arg.PrincipalID,
		arg.PolicyVersion,
		arg.MemoryKib,
		arg.TimeCost,
		arg.Parallelism,
		arg.Salt,
		arg.PasswordHash,
		arg.UpdatedAt,
	)
	return err
}

const createRecoveryCodeSet = `-- name: CreateRecoveryCodeSet :exec
INSERT INTO identity.recovery_code_sets
  (id, principal_id, generation, code_hashes, state, created_at, updated_at)
VALUES ($1,$2,$3,$4,'active',$5,$5)
`

type CreateRecoveryCodeSetParams struct {
	ID          uuid.UUID `json:"id"`
	PrincipalID uuid.UUID `json:"principal_id"`
	Generation  int32     `json:"generation"`
	CodeHashes  [][]byte  `json:"code_hashes"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) CreateRecoveryCodeSet(ctx context.Context, arg CreateRecoveryCodeSetParams) error {
	_, err := q.db.Exec(ctx, createRecoveryCodeSet,
		arg.ID,
		arg.PrincipalID,
		arg.Generation,
		arg.CodeHashes,
		arg.CreatedAt,
	)
	return err
}

const createTOTPEnrollment = `-- name: CreateTOTPEnrollment :exec
INSERT INTO identity.totp_credentials
  (principal_id, ciphertext, encryption_key_version, state, created_at)
VALUES ($1,$2,$3,'pending',$4)
`

type CreateTOTPEnrollmentParams struct {
	PrincipalID          uuid.UUID `json:"principal_id"`
	Ciphertext           []byte    `json:"ciphertext"`
	EncryptionKeyVersion int32     `json:"encryption_key_version"`
	CreatedAt            time.Time `json:"created_at"`
}

func (q *Queries) CreateTOTPEnrollment(ctx context.Context, arg CreateTOTPEnrollmentParams) error {
	_, err := q.db.Exec(ctx, createTOTPEnrollment,
		arg.PrincipalID,
		arg.Ciphertext,
		arg.EncryptionKeyVersion,
		arg.CreatedAt,
	)
	return err
}

const findAccountAccessToken = `-- name: FindAccountAccessToken :one
SELECT s.id, s.principal_id, s.state, s.state_version, s.access_expires_at,
       s.absolute_expires_at, a.state AS account_state
FROM identity.account_sessions s
JOIN identity.accounts a ON a.id=s.principal_id
WHERE s.access_token_hash=$1
`

type FindAccountAccessTokenRow struct {
	ID                uuid.UUID `json:"id"`
	PrincipalID       uuid.UUID `json:"principal_id"`
	State             string    `json:"state"`
	StateVersion      int64     `json:"state_version"`
	AccessExpiresAt   time.Time `json:"access_expires_at"`
	AbsoluteExpiresAt time.Time `json:"absolute_expires_at"`
	AccountState      string    `json:"account_state"`
}

func (q *Queries) FindAccountAccessToken(ctx context.Context, accessTokenHash []byte) (FindAccountAccessTokenRow, error) {
	row := q.db.QueryRow(ctx, findAccountAccessToken, accessTokenHash)
	var i FindAccountAccessTokenRow
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.State,
		&i.StateVersion,
		&i.AccessExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.AccountState,
	)
	return i, err
}

const findIdentityByLookupDigest = `-- name: FindIdentityByLookupDigest :one
SELECT id, principal_id, lookup_key_version, lookup_digest, ciphertext, encryption_key_version, verification_token_hash, verification_expires_at, verification_consumed_at, verification_delivery_id, verification_delivery_ciphertext, verification_delivery_key_version, verified_at, created_at, updated_at FROM identity.email_identities WHERE lookup_digest = $1 FOR UPDATE
`

func (q *Queries) FindIdentityByLookupDigest(ctx context.Context, lookupDigest []byte) (IdentityEmailIdentity, error) {
	row := q.db.QueryRow(ctx, findIdentityByLookupDigest, lookupDigest)
	var i IdentityEmailIdentity
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.LookupKeyVersion,
		&i.LookupDigest,
		&i.Ciphertext,
		&i.EncryptionKeyVersion,
		&i.VerificationTokenHash,
		&i.VerificationExpiresAt,
		&i.VerificationConsumedAt,
		&i.VerificationDeliveryID,
		&i.VerificationDeliveryCiphertext,
		&i.VerificationDeliveryKeyVersion,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT id, state, state_version, locale, created_at, updated_at FROM identity.accounts WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetAccountForUpdate(ctx context.Context, id uuid.UUID) (IdentityAccount, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdate, id)
	var i IdentityAccount
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.StateVersion,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountSessionForUpdate = `-- name: GetAccountSessionForUpdate :one
SELECT id, principal_id, state, state_version, client_signing_public_key, access_token_hash, access_expires_at, absolute_expires_at, created_at, updated_at, device_authorization_id FROM identity.account_sessions
WHERE id = $1 AND principal_id = $2
FOR UPDATE
`

type GetAccountSessionForUpdateParams struct {
	ID          uuid.UUID `json:"id"`
	PrincipalID uuid.UUID `json:"principal_id"`
}

func (q *Queries) GetAccountSessionForUpdate(ctx context.Context, arg GetAccountSessionForUpdateParams) (IdentityAccountSession, error) {
	row := q.db.QueryRow(ctx, getAccountSessionForUpdate, arg.ID, arg.PrincipalID)
	var i IdentityAccountSession
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.State,
		&i.StateVersion,
		&i.ClientSigningPublicKey,
		&i.AccessTokenHash,
		&i.AccessExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeviceAuthorizationID,
	)
	return i, err
}

const getActiveRecoveryCodeSetForUpdate = `-- name: GetActiveRecoveryCodeSetForUpdate :one
SELECT id, principal_id, generation, code_hashes, state, created_at, updated_at FROM identity.recovery_code_sets
WHERE principal_id=$1 AND state='active' FOR UPDATE
`

func (q *Queries) GetActiveRecoveryCodeSetForUpdate(ctx context.Context, principalID uuid.UUID) (IdentityRecoveryCodeSet, error) {
	row := q.db.QueryRow(ctx, getActiveRecoveryCodeSetForUpdate, principalID)
	var i IdentityRecoveryCodeSet
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.Generation,
		&i.CodeHashes,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmailVerificationForUpdate = `-- name: GetEmailVerificationForUpdate :one
SELECT id, principal_id, lookup_key_version, lookup_digest, ciphertext, encryption_key_version, verification_token_hash, verification_expires_at, verification_consumed_at, verification_delivery_id, verification_delivery_ciphertext, verification_delivery_key_version, verified_at, created_at, updated_at FROM identity.email_identities
WHERE verification_token_hash = $1
FOR UPDATE
`

func (q *Queries) GetEmailVerificationForUpdate(ctx context.Context, verificationTokenHash []byte) (IdentityEmailIdentity, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationForUpdate, verificationTokenHash)
	var i IdentityEmailIdentity
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.LookupKeyVersion,
		&i.LookupDigest,
		&i.Ciphertext,
		&i.EncryptionKeyVersion,
		&i.VerificationTokenHash,
		&i.VerificationExpiresAt,
		&i.VerificationConsumedAt,
		&i.VerificationDeliveryID,
		&i.VerificationDeliveryCiphertext,
		&i.VerificationDeliveryKeyVersion,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPasswordCredential = `-- name: GetPasswordCredential :one
SELECT principal_id, policy_version, memory_kib, time_cost, parallelism, salt, password_hash, reset_token_hash, reset_expires_at, reset_consumed_at, reset_delivery_id, reset_delivery_ciphertext, reset_delivery_key_version, updated_at FROM identity.password_credentials WHERE principal_id = $1
`

func (q *Queries) GetPasswordCredential(ctx context.Context, principalID uuid.UUID) (IdentityPasswordCredential, error) {
	row := q.db.QueryRow(ctx, getPasswordCredential, principalID)
	var i IdentityPasswordCredential
	err := row.Scan(
		&i.PrincipalID,
		&i.PolicyVersion,
		&i.MemoryKib,
		&i.TimeCost,
		&i.Parallelism,
		&i.Salt,
		&i.PasswordHash,
		&i.ResetTokenHash,
		&i.ResetExpiresAt,
		&i.ResetConsumedAt,
		&i.ResetDeliveryID,
		&i.ResetDeliveryCiphertext,
		&i.ResetDeliveryKeyVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingEmailDelivery = `-- name: GetPendingEmailDelivery :one
SELECT verification_delivery_id, verification_delivery_ciphertext,
       verification_delivery_key_version, verification_expires_at
FROM identity.email_identities
WHERE verification_delivery_id=$1 AND verification_consumed_at IS NULL
`

type GetPendingEmailDeliveryRow struct {
	VerificationDeliveryID         uuid.NullUUID `json:"verification_delivery_id"`
	VerificationDeliveryCiphertext []byte        `json:"verification_delivery_ciphertext"`
	VerificationDeliveryKeyVersion pgtype.Int4   `json:"verification_delivery_key_version"`
	VerificationExpiresAt          sql.NullTime  `json:"verification_expires_at"`
}

func (q *Queries) GetPendingEmailDelivery(ctx context.Context, verificationDeliveryID uuid.NullUUID) (GetPendingEmailDeliveryRow, error) {
	row := q.db.QueryRow(ctx, getPendingEmailDelivery, verificationDeliveryID)
	var i GetPendingEmailDeliveryRow
	err := row.Scan(
		&i.VerificationDeliveryID,
		&i.VerificationDeliveryCiphertext,
		&i.VerificationDeliveryKeyVersion,
		&i.VerificationExpiresAt,
	)
	return i, err
}

const getPendingPasswordResetDelivery = `-- name: GetPendingPasswordResetDelivery :one
SELECT reset_delivery_id, reset_delivery_ciphertext, reset_delivery_key_version, reset_expires_at
FROM identity.password_credentials
WHERE reset_delivery_id=$1 AND reset_consumed_at IS NULL
`

type GetPendingPasswordResetDeliveryRow struct {
	ResetDeliveryID         uuid.NullUUID `json:"reset_delivery_id"`
	ResetDeliveryCiphertext []byte        `json:"reset_delivery_ciphertext"`
	ResetDeliveryKeyVersion pgtype.Int4   `json:"reset_delivery_key_version"`
	ResetExpiresAt          sql.NullTime  `json:"reset_expires_at"`
}

func (q *Queries) GetPendingPasswordResetDelivery(ctx context.Context, resetDeliveryID uuid.NullUUID) (GetPendingPasswordResetDeliveryRow, error) {
	row := q.db.QueryRow(ctx, getPendingPasswordResetDelivery, resetDeliveryID)
	var i GetPendingPasswordResetDeliveryRow
	err := row.Scan(
		&i.ResetDeliveryID,
		&i.ResetDeliveryCiphertext,
		&i.ResetDeliveryKeyVersion,
		&i.ResetExpiresAt,
	)
	return i, err
}

const getRefreshTokenForUpdate = `-- name: GetRefreshTokenForUpdate :one
WITH locked_refresh AS MATERIALIZED (
  SELECT r.token_hash, r.session_id, r.previous_token_hash, r.state,
         r.issued_at, r.idle_expires_at, r.absolute_expires_at, r.used_at, r.revoked_at
  FROM identity.account_refresh_tokens r
  WHERE r.token_hash=$1
  FOR UPDATE OF r
), locked_session AS MATERIALIZED (
  SELECT s.id, s.state, s.state_version, s.client_signing_public_key, s.principal_id
  FROM identity.account_sessions s
  JOIN locked_refresh r ON r.session_id=s.id
  WHERE (SELECT count(*) FROM locked_refresh) >= 0
  FOR UPDATE OF s
), locked_account AS MATERIALIZED (
  SELECT a.id, a.state
  FROM identity.accounts a
  JOIN locked_session s ON s.principal_id=a.id
  WHERE (SELECT count(*) FROM locked_session) >= 0
  FOR UPDATE OF a
)
SELECT r.token_hash, r.session_id, r.previous_token_hash, r.state AS refresh_state,
       r.issued_at, r.idle_expires_at, r.absolute_expires_at, r.used_at, r.revoked_at,
       s.state AS session_state, s.state_version AS session_state_version,
       s.client_signing_public_key, s.principal_id, a.state AS account_state
FROM locked_refresh r
JOIN locked_session s ON s.id=r.session_id
JOIN locked_account a ON a.id=s.principal_id
`

type GetRefreshTokenForUpdateRow struct {
	TokenHash              []byte       `json:"token_hash"`
	SessionID              uuid.UUID    `json:"session_id"`
	PreviousTokenHash      []byte       `json:"previous_token_hash"`
	RefreshState           string       `json:"refresh_state"`
	IssuedAt               time.Time    `json:"issued_at"`
	IdleExpiresAt          time.Time    `json:"idle_expires_at"`
	AbsoluteExpiresAt      time.Time    `json:"absolute_expires_at"`
	UsedAt                 sql.NullTime `json:"used_at"`
	RevokedAt              sql.NullTime `json:"revoked_at"`
	SessionState           string       `json:"session_state"`
	SessionStateVersion    int64        `json:"session_state_version"`
	ClientSigningPublicKey []byte       `json:"client_signing_public_key"`
	PrincipalID            uuid.UUID    `json:"principal_id"`
	AccountState           string       `json:"account_state"`
}

func (q *Queries) GetRefreshTokenForUpdate(ctx context.Context, tokenHash []byte) (GetRefreshTokenForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForUpdate, tokenHash)
	var i GetRefreshTokenForUpdateRow
	err := row.Scan(
		&i.TokenHash,
		&i.SessionID,
		&i.PreviousTokenHash,
		&i.RefreshState,
		&i.IssuedAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.SessionState,
		&i.SessionStateVersion,
		&i.ClientSigningPublicKey,
		&i.PrincipalID,
		&i.AccountState,
	)
	return i, err
}

const getTOTPForUpdate = `-- name: GetTOTPForUpdate :one
SELECT principal_id, ciphertext, encryption_key_version, state, last_accepted_step, created_at, verified_at, revoked_at FROM identity.totp_credentials WHERE principal_id=$1 FOR UPDATE
`

func (q *Queries) GetTOTPForUpdate(ctx context.Context, principalID uuid.UUID) (IdentityTotpCredential, error) {
	row := q.db.QueryRow(ctx, getTOTPForUpdate, principalID)
	var i IdentityTotpCredential
	err := row.Scan(
		&i.PrincipalID,
		&i.Ciphertext,
		&i.EncryptionKeyVersion,
		&i.State,
		&i.LastAcceptedStep,
		&i.CreatedAt,
		&i.VerifiedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertAccountRefreshToken = `-- name: InsertAccountRefreshToken :exec
INSERT INTO identity.account_refresh_tokens
  (token_hash, session_id, previous_token_hash, state, issued_at, idle_expires_at, absolute_expires_at)
VALUES ($1,$2,$3,'active',$4,$5,$6)
`

type InsertAccountRefreshTokenParams struct {
	TokenHash         []byte    `json:"token_hash"`
	SessionID         uuid.UUID `json:"session_id"`
	PreviousTokenHash []byte    `json:"previous_token_hash"`
	IssuedAt          time.Time `json:"issued_at"`
	IdleExpiresAt     time.Time `json:"idle_expires_at"`
	AbsoluteExpiresAt time.Time `json:"absolute_expires_at"`
}

func (q *Queries) InsertAccountRefreshToken(ctx context.Context, arg InsertAccountRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertAccountRefreshToken,
		arg.TokenHash,
		arg.SessionID,
		arg.PreviousTokenHash,
		arg.IssuedAt,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
	)
	return err
}

const insertSecurityEvent = `-- name: InsertSecurityEvent :exec
INSERT INTO identity.security_events
  (id, principal_id, category, fingerprint, aggregate_version, occurred_at)
VALUES ($1,$2,$3,$4,$5,$6)
`

type InsertSecurityEventParams struct {
	ID               uuid.UUID     `json:"id"`
	PrincipalID      uuid.NullUUID `json:"principal_id"`
	Category         string        `json:"category"`
	Fingerprint      string        `json:"fingerprint"`
	AggregateVersion int64         `json:"aggregate_version"`
	OccurredAt       time.Time     `json:"occurred_at"`
}

func (q *Queries) InsertSecurityEvent(ctx context.Context, arg InsertSecurityEventParams) error {
	_, err := q.db.Exec(ctx, insertSecurityEvent,
		arg.ID,
		arg.PrincipalID,
		arg.Category,
		arg.Fingerprint,
		arg.AggregateVersion,
		arg.OccurredAt,
	)
	return err
}

const listActivePasskeys = `-- name: ListActivePasskeys :many
SELECT credential_id, principal_id, public_key, attestation_format, transports, protocol_flags, sign_count, state, created_at, updated_at, revoked_at FROM identity.passkey_credentials
WHERE principal_id=$1 AND state='active'
ORDER BY created_at LIMIT 10
`

func (q *Queries) ListActivePasskeys(ctx context.Context, principalID uuid.UUID) ([]IdentityPasskeyCredential, error) {
	rows, err := q.db.Query(ctx, listActivePasskeys, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityPasskeyCredential{}
	for rows.Next() {
		var i IdentityPasskeyCredential
		if err := rows.Scan(
			&i.CredentialID,
			&i.PrincipalID,
			&i.PublicKey,
			&i.AttestationFormat,
			&i.Transports,
			&i.ProtocolFlags,
			&i.SignCount,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEmailLookupDigest = `-- name: LockEmailLookupDigest :exec
SELECT pg_advisory_xact_lock(
  hashtextextended(encode($1::bytea, 'hex'), 0)
)
`

func (q *Queries) LockEmailLookupDigest(ctx context.Context, lookupDigest []byte) error {
	_, err := q.db.Exec(ctx, lockEmailLookupDigest, lookupDigest)
	return err
}

const markAccountRefreshUsed = `-- name: MarkAccountRefreshUsed :one
UPDATE identity.account_refresh_tokens
SET state = 'used', used_at = $2
WHERE token_hash = $1 AND state = 'active'
RETURNING token_hash, session_id, previous_token_hash, state, issued_at, idle_expires_at, absolute_expires_at, used_at, revoked_at
`

type MarkAccountRefreshUsedParams struct {
	TokenHash []byte       `json:"token_hash"`
	UsedAt    sql.NullTime `json:"used_at"`
}

func (q *Queries) MarkAccountRefreshUsed(ctx context.Context, arg MarkAccountRefreshUsedParams) (IdentityAccountRefreshToken, error) {
	row := q.db.QueryRow(ctx, markAccountRefreshUsed, arg.TokenHash, arg.UsedAt)
	var i IdentityAccountRefreshToken
	err := row.Scan(
		&i.TokenHash,
		&i.SessionID,
		&i.PreviousTokenHash,
		&i.State,
		&i.IssuedAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const markAccountSessionCompromised = `-- name: MarkAccountSessionCompromised :execrows
UPDATE identity.account_sessions
SET state='compromised', state_version=state_version+1, updated_at=$2
WHERE id=$1 AND state IN ('active','review_required')
`

type MarkAccountSessionCompromisedParams struct {
	ID        uuid.UUID `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) MarkAccountSessionCompromised(ctx context.Context, arg MarkAccountSessionCompromisedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAccountSessionCompromised, arg.ID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markPrincipalSessionsReviewRequired = `-- name: MarkPrincipalSessionsReviewRequired :execrows
UPDATE identity.account_sessions
SET state='review_required', state_version=state_version+1, updated_at=$2
WHERE principal_id=$1 AND state='active'
`

type MarkPrincipalSessionsReviewRequiredParams struct {
	PrincipalID uuid.UUID `json:"principal_id"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) MarkPrincipalSessionsReviewRequired(ctx context.Context, arg MarkPrincipalSessionsReviewRequiredParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPrincipalSessionsReviewRequired, arg.PrincipalID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetEmailVerification = `-- name: ResetEmailVerification :one
UPDATE identity.email_identities
SET verification_token_hash = $2, verification_expires_at = $3,
    verification_consumed_at = NULL, verification_delivery_id=$4,
    verification_delivery_ciphertext=$5, verification_delivery_key_version=$6, updated_at=$7
WHERE principal_id = $1 AND verified_at IS NULL
RETURNING id, principal_id, lookup_key_version, lookup_digest, ciphertext, encryption_key_version, verification_token_hash, verification_expires_at, verification_consumed_at, verification_delivery_id, verification_delivery_ciphertext, verification_delivery_key_version, verified_at, created_at, updated_at
`

type ResetEmailVerificationParams struct {
	PrincipalID                    uuid.UUID     `json:"principal_id"`
	VerificationTokenHash          []byte        `json:"verification_token_hash"`
	VerificationExpiresAt          sql.NullTime  `json:"verification_expires_at"`
	VerificationDeliveryID         uuid.NullUUID `json:"verification_delivery_id"`
	VerificationDeliveryCiphertext []byte        `json:"verification_delivery_ciphertext"`
	VerificationDeliveryKeyVersion pgtype.Int4   `json:"verification_delivery_key_version"`
	UpdatedAt                      time.Time     `json:"updated_at"`
}

func (q *Queries) ResetEmailVerification(ctx context.Context, arg ResetEmailVerificationParams) (IdentityEmailIdentity, error) {
	row := q.db.QueryRow(ctx, resetEmailVerification,
		arg.PrincipalID,
		arg.VerificationTokenHash,
		arg.VerificationExpiresAt,
		arg.VerificationDeliveryID,
		arg.VerificationDeliveryCiphertext,
		arg.VerificationDeliveryKeyVersion,
		arg.UpdatedAt,
	)
	var i IdentityEmailIdentity
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.LookupKeyVersion,
		&i.LookupDigest,
		&i.Ciphertext,
		&i.EncryptionKeyVersion,
		&i.VerificationTokenHash,
		&i.VerificationExpiresAt,
		&i.VerificationConsumedAt,
		&i.VerificationDeliveryID,
		&i.VerificationDeliveryCiphertext,
		&i.VerificationDeliveryKeyVersion,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeAccountRefreshTokens = `-- name: RevokeAccountRefreshTokens :execrows
UPDATE identity.account_refresh_tokens
SET state='revoked', revoked_at=$2
WHERE session_id=$1 AND state='active'
`

type RevokeAccountRefreshTokensParams struct {
	SessionID uuid.UUID    `json:"session_id"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

func (q *Queries) RevokeAccountRefreshTokens(ctx context.Context, arg RevokeAccountRefreshTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAccountRefreshTokens, arg.SessionID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAccountSession = `-- name: RevokeAccountSession :execrows
UPDATE identity.account_sessions
SET state = 'revoked', state_version = state_version + 1, updated_at = $2
WHERE id = $1 AND state IN ('active','review_required')
`

type RevokeAccountSessionParams struct {
	ID        uuid.UUID `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) RevokeAccountSession(ctx context.Context, arg RevokeAccountSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAccountSession, arg.ID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokePasskey = `-- name: RevokePasskey :execrows
UPDATE identity.passkey_credentials
SET state='revoked', revoked_at=$3, updated_at=$3
WHERE credential_id=$1 AND principal_id=$2 AND state='active'
`

type RevokePasskeyParams struct {
	CredentialID []byte       `json:"credential_id"`
	PrincipalID  uuid.UUID    `json:"principal_id"`
	RevokedAt    sql.NullTime `json:"revoked_at"`
}

func (q *Queries) RevokePasskey(ctx context.Context, arg RevokePasskeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokePasskey, arg.CredentialID, arg.PrincipalID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokePrincipalAccountSessions = `-- name: RevokePrincipalAccountSessions :many
WITH target_refresh AS MATERIALIZED (
  SELECT r.token_hash, r.session_id
  FROM identity.account_refresh_tokens r
  JOIN identity.account_sessions s ON s.id=r.session_id
  WHERE s.principal_id=$2
    AND (
      $3::text='all'
      OR ($3::text='current' AND s.id=$4)
      OR ($3::text='others' AND s.id<>$4)
    )
  ORDER BY r.token_hash
  FOR UPDATE OF r
), target_sessions AS MATERIALIZED (
  SELECT s.id
  FROM identity.account_sessions s
  WHERE s.id IN (SELECT session_id FROM target_refresh)
  ORDER BY s.id
  FOR UPDATE OF s
), locked_account AS MATERIALIZED (
  SELECT a.id
  FROM identity.accounts a
  WHERE a.id=$2
    AND EXISTS (SELECT 1 FROM target_sessions)
  FOR UPDATE OF a
), revoked_refresh AS (
  UPDATE identity.account_refresh_tokens r
  SET state='revoked', revoked_at=$1
  WHERE r.token_hash IN (SELECT token_hash FROM target_refresh)
    AND r.state='active'
    AND EXISTS (SELECT 1 FROM locked_account)
  RETURNING r.session_id
)
UPDATE identity.account_sessions s
SET state='revoked', state_version=state_version+1, updated_at=$1
WHERE s.id IN (SELECT id FROM target_sessions)
  AND s.state IN ('active','review_required')
  AND (SELECT count(*) FROM revoked_refresh) >= 0
RETURNING s.id
`

type RevokePrincipalAccountSessionsParams struct {
	RevokedAt   time.Time `json:"revoked_at"`
	PrincipalID uuid.UUID `json:"principal_id"`
	RevokeScope string    `json:"revoke_scope"`
	SessionID   uuid.UUID `json:"session_id"`
}

func (q *Queries) RevokePrincipalAccountSessions(ctx context.Context, arg RevokePrincipalAccountSessionsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokePrincipalAccountSessions,
		arg.RevokedAt,
		arg.PrincipalID,
		arg.RevokeScope,
		arg.SessionID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRecoveryCodeSets = `-- name: RevokeRecoveryCodeSets :execrows
UPDATE identity.recovery_code_sets
SET state=$2, updated_at=$3
WHERE principal_id=$1 AND state='active' AND $2 IN ('superseded','revoked')
`

type RevokeRecoveryCodeSetsParams struct {
	PrincipalID uuid.UUID `json:"principal_id"`
	State       string    `json:"state"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) RevokeRecoveryCodeSets(ctx context.Context, arg RevokeRecoveryCodeSetsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRecoveryCodeSets, arg.PrincipalID, arg.State, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeTOTP = `-- name: RevokeTOTP :execrows
UPDATE identity.totp_credentials
SET state='revoked', revoked_at=$2
WHERE principal_id=$1 AND state IN ('pending','active')
`

type RevokeTOTPParams struct {
	PrincipalID uuid.UUID    `json:"principal_id"`
	RevokedAt   sql.NullTime `json:"revoked_at"`
}

func (q *Queries) RevokeTOTP(ctx context.Context, arg RevokeTOTPParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeTOTP, arg.PrincipalID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateAccountSessionAccess = `-- name: RotateAccountSessionAccess :one
UPDATE identity.account_sessions
SET access_token_hash=$2, access_expires_at=$3, updated_at=$4,
    state_version=state_version+1
WHERE id=$1 AND state='active' AND absolute_expires_at >= $4
RETURNING id, principal_id, state, state_version, client_signing_public_key, access_token_hash, access_expires_at, absolute_expires_at, created_at, updated_at, device_authorization_id
`

type RotateAccountSessionAccessParams struct {
	ID              uuid.UUID `json:"id"`
	AccessTokenHash []byte    `json:"access_token_hash"`
	AccessExpiresAt time.Time `json:"access_expires_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) RotateAccountSessionAccess(ctx context.Context, arg RotateAccountSessionAccessParams) (IdentityAccountSession, error) {
	row := q.db.QueryRow(ctx, rotateAccountSessionAccess,
		arg.ID,
		arg.AccessTokenHash,
		arg.AccessExpiresAt,
		arg.UpdatedAt,
	)
	var i IdentityAccountSession
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.State,
		&i.StateVersion,
		&i.ClientSigningPublicKey,
		&i.AccessTokenHash,
		&i.AccessExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeviceAuthorizationID,
	)
	return i, err
}

const setPasswordReset = `-- name: SetPasswordReset :one
UPDATE identity.password_credentials
SET reset_token_hash=$2, reset_expires_at=$3, reset_consumed_at=NULL,
    reset_delivery_id=$4, reset_delivery_ciphertext=$5,
    reset_delivery_key_version=$6, updated_at=$7
WHERE principal_id=$1
RETURNING principal_id, policy_version, memory_kib, time_cost, parallelism, salt, password_hash, reset_token_hash, reset_expires_at, reset_consumed_at, reset_delivery_id, reset_delivery_ciphertext, reset_delivery_key_version, updated_at
`

type SetPasswordResetParams struct {
	PrincipalID             uuid.UUID     `json:"principal_id"`
	ResetTokenHash          []byte        `json:"reset_token_hash"`
	ResetExpiresAt          sql.NullTime  `json:"reset_expires_at"`
	ResetDeliveryID         uuid.NullUUID `json:"reset_delivery_id"`
	ResetDeliveryCiphertext []byte        `json:"reset_delivery_ciphertext"`
	ResetDeliveryKeyVersion pgtype.Int4   `json:"reset_delivery_key_version"`
	UpdatedAt               time.Time     `json:"updated_at"`
}

func (q *Queries) SetPasswordReset(ctx context.Context, arg SetPasswordResetParams) (IdentityPasswordCredential, error) {
	row := q.db.QueryRow(ctx, setPasswordReset,
		arg.PrincipalID,
		arg.ResetTokenHash,
		arg.ResetExpiresAt,
		arg.ResetDeliveryID,
		arg.ResetDeliveryCiphertext,
		arg.ResetDeliveryKeyVersion,
		arg.UpdatedAt,
	)
	var i IdentityPasswordCredential
	err := row.Scan(
		&i.PrincipalID,
		&i.PolicyVersion,
		&i.MemoryKib,
		&i.TimeCost,
		&i.Parallelism,
		&i.Salt,
		&i.PasswordHash,
		&i.ResetTokenHash,
		&i.ResetExpiresAt,
		&i.ResetConsumedAt,
		&i.ResetDeliveryID,
		&i.ResetDeliveryCiphertext,
		&i.ResetDeliveryKeyVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePasskeyCounter = `-- name: UpdatePasskeyCounter :execrows
UPDATE identity.passkey_credentials
SET sign_count=$3, protocol_flags=$4, updated_at=$5
WHERE credential_id=$1 AND principal_id=$2 AND state='active' AND sign_count <= $3
`

type UpdatePasskeyCounterParams struct {
	CredentialID  []byte    `json:"credential_id"`
	PrincipalID   uuid.UUID `json:"principal_id"`
	SignCount     int64     `json:"sign_count"`
	ProtocolFlags int16     `json:"protocol_flags"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) UpdatePasskeyCounter(ctx context.Context, arg UpdatePasskeyCounterParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePasskeyCounter,
		arg.CredentialID,
		arg.PrincipalID,
		arg.SignCount,
		arg.ProtocolFlags,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePasswordCredential = `-- name: UpdatePasswordCredential :execrows
UPDATE identity.password_credentials
SET policy_version=$2, memory_kib=$3, time_cost=$4, parallelism=$5,
    salt=$6, password_hash=$7, updated_at=$8
WHERE principal_id=$1
`

type UpdatePasswordCredentialParams struct {
	PrincipalID   uuid.UUID `json:"principal_id"`
	PolicyVersion int32     `json:"policy_version"`
	MemoryKib     int32     `json:"memory_kib"`
	TimeCost      int32     `json:"time_cost"`
	Parallelism   int32     `json:"parallelism"`
	Salt          []byte    `json:"salt"`
	PasswordHash  []byte    `json:"password_hash"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) UpdatePasswordCredential(ctx context.Context, arg UpdatePasswordCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePasswordCredential,
		arg.PrincipalID,
		arg.PolicyVersion,
		arg.MemoryKib,
		arg.TimeCost,
		arg.Parallelism,
		arg.Salt,
		arg.PasswordHash,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
