// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type SystemMetadatum struct {
	Key       string             `json:"key"`
	Value     json.RawMessage    `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
