// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodecontrol_authority.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const abortAuthorityFence = `-- name: AbortAuthorityFence :execrows
UPDATE nodecontrol.control_plane_authority_fences
SET provider_status = 'aborted', provider_receipt_digest = $2, abort_reason = $3,
    visibility_state = 'aborted', terminal_at = $4
WHERE operation_id = $1 AND provider_status = 'reserved' AND visibility_state = 'fence_pending'
`

type AbortAuthorityFenceParams struct {
	OperationID           uuid.UUID          `json:"operation_id"`
	ProviderReceiptDigest []byte             `json:"provider_receipt_digest"`
	AbortReason           pgtype.Text        `json:"abort_reason"`
	TerminalAt            pgtype.Timestamptz `json:"terminal_at"`
}

func (q *Queries) AbortAuthorityFence(ctx context.Context, arg AbortAuthorityFenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, abortAuthorityFence,
		arg.OperationID,
		arg.ProviderReceiptDigest,
		arg.AbortReason,
		arg.TerminalAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const activateCommittedAuthorityFence = `-- name: ActivateCommittedAuthorityFence :execrows
UPDATE nodecontrol.control_plane_authority_fences
SET provider_status = 'committed', provider_receipt_digest = $2, visibility_state = 'active', terminal_at = $3
WHERE operation_id = $1 AND provider_status = 'reserved' AND visibility_state = 'fence_pending'
  AND effect_digest = $4 AND db_system_id = $5 AND db_timeline = $6 AND required_lsn = $7
`

type ActivateCommittedAuthorityFenceParams struct {
	OperationID           uuid.UUID          `json:"operation_id"`
	ProviderReceiptDigest []byte             `json:"provider_receipt_digest"`
	TerminalAt            pgtype.Timestamptz `json:"terminal_at"`
	EffectDigest          []byte             `json:"effect_digest"`
	DbSystemID            pgtype.Numeric     `json:"db_system_id"`
	DbTimeline            pgtype.Int8        `json:"db_timeline"`
	RequiredLsn           interface{}        `json:"required_lsn"`
}

func (q *Queries) ActivateCommittedAuthorityFence(ctx context.Context, arg ActivateCommittedAuthorityFenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, activateCommittedAuthorityFence,
		arg.OperationID,
		arg.ProviderReceiptDigest,
		arg.TerminalAt,
		arg.EffectDigest,
		arg.DbSystemID,
		arg.DbTimeline,
		arg.RequiredLsn,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bindAuthorityFenceEffect = `-- name: BindAuthorityFenceEffect :execrows
UPDATE nodecontrol.control_plane_authority_fences
SET effect_digest = $2, db_system_id = $3, db_timeline = $4,
    required_lsn = $5, effect_bound_at = $6
WHERE operation_id = $1 AND provider_status = 'reserved' AND visibility_state = 'fence_pending'
  AND effect_digest IS NULL
`

type BindAuthorityFenceEffectParams struct {
	OperationID   uuid.UUID          `json:"operation_id"`
	EffectDigest  []byte             `json:"effect_digest"`
	DbSystemID    pgtype.Numeric     `json:"db_system_id"`
	DbTimeline    pgtype.Int8        `json:"db_timeline"`
	RequiredLsn   interface{}        `json:"required_lsn"`
	EffectBoundAt pgtype.Timestamptz `json:"effect_bound_at"`
}

func (q *Queries) BindAuthorityFenceEffect(ctx context.Context, arg BindAuthorityFenceEffectParams) (int64, error) {
	result, err := q.db.Exec(ctx, bindAuthorityFenceEffect,
		arg.OperationID,
		arg.EffectDigest,
		arg.DbSystemID,
		arg.DbTimeline,
		arg.RequiredLsn,
		arg.EffectBoundAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAuthorityFence = `-- name: GetAuthorityFence :one
SELECT operation_id, effect_kind, scope_kind, authority_epoch, authority_sequence, scope_digest, provider_reservation_digest, effect_digest, provider_status, provider_receipt_digest, db_system_id, db_timeline, required_lsn, abort_reason, visibility_state, reserved_at, effect_bound_at, terminal_at FROM nodecontrol.control_plane_authority_fences WHERE operation_id = $1
`

func (q *Queries) GetAuthorityFence(ctx context.Context, operationID uuid.UUID) (NodecontrolControlPlaneAuthorityFence, error) {
	row := q.db.QueryRow(ctx, getAuthorityFence, operationID)
	var i NodecontrolControlPlaneAuthorityFence
	err := row.Scan(
		&i.OperationID,
		&i.EffectKind,
		&i.ScopeKind,
		&i.AuthorityEpoch,
		&i.AuthoritySequence,
		&i.ScopeDigest,
		&i.ProviderReservationDigest,
		&i.EffectDigest,
		&i.ProviderStatus,
		&i.ProviderReceiptDigest,
		&i.DbSystemID,
		&i.DbTimeline,
		&i.RequiredLsn,
		&i.AbortReason,
		&i.VisibilityState,
		&i.ReservedAt,
		&i.EffectBoundAt,
		&i.TerminalAt,
	)
	return i, err
}

const getAuthorityFenceForUpdate = `-- name: GetAuthorityFenceForUpdate :one
SELECT operation_id, effect_kind, scope_kind, authority_epoch, authority_sequence, scope_digest, provider_reservation_digest, effect_digest, provider_status, provider_receipt_digest, db_system_id, db_timeline, required_lsn, abort_reason, visibility_state, reserved_at, effect_bound_at, terminal_at FROM nodecontrol.control_plane_authority_fences
WHERE operation_id = $1
FOR UPDATE
`

func (q *Queries) GetAuthorityFenceForUpdate(ctx context.Context, operationID uuid.UUID) (NodecontrolControlPlaneAuthorityFence, error) {
	row := q.db.QueryRow(ctx, getAuthorityFenceForUpdate, operationID)
	var i NodecontrolControlPlaneAuthorityFence
	err := row.Scan(
		&i.OperationID,
		&i.EffectKind,
		&i.ScopeKind,
		&i.AuthorityEpoch,
		&i.AuthoritySequence,
		&i.ScopeDigest,
		&i.ProviderReservationDigest,
		&i.EffectDigest,
		&i.ProviderStatus,
		&i.ProviderReceiptDigest,
		&i.DbSystemID,
		&i.DbTimeline,
		&i.RequiredLsn,
		&i.AbortReason,
		&i.VisibilityState,
		&i.ReservedAt,
		&i.EffectBoundAt,
		&i.TerminalAt,
	)
	return i, err
}

const getAuthorityFenceHead = `-- name: GetAuthorityFenceHead :one
WITH latest_epoch AS (
  SELECT COALESCE(MAX(authority_epoch), 0)::bigint AS authority_epoch
  FROM nodecontrol.control_plane_authority_fences
), epoch_rows AS (
  SELECT f.operation_id, f.effect_kind, f.scope_kind, f.authority_epoch, f.authority_sequence, f.scope_digest, f.provider_reservation_digest, f.effect_digest, f.provider_status, f.provider_receipt_digest, f.db_system_id, f.db_timeline, f.required_lsn, f.abort_reason, f.visibility_state, f.reserved_at, f.effect_bound_at, f.terminal_at FROM nodecontrol.control_plane_authority_fences f
  JOIN latest_epoch e ON f.authority_epoch = e.authority_epoch
), aggregate_head AS (
  SELECT COUNT(*)::bigint AS record_count,
         COALESCE(MAX(authority_sequence), 0)::bigint AS latest_reserved_sequence,
         COALESCE(MAX(authority_sequence) FILTER (
           WHERE provider_status = 'committed' AND visibility_state = 'active'), 0)::bigint AS latest_committed_sequence,
         COUNT(*) FILTER (WHERE provider_status = 'reserved')::bigint AS pending_count
  FROM epoch_rows
), latest_record AS (
  SELECT provider_reservation_digest FROM epoch_rows ORDER BY authority_sequence DESC LIMIT 1
), latest_committed AS (
  SELECT operation_id, provider_receipt_digest, db_system_id, db_timeline, required_lsn
  FROM epoch_rows
  WHERE provider_status = 'committed' AND visibility_state = 'active'
  ORDER BY authority_sequence DESC LIMIT 1
)
SELECT e.authority_epoch, a.record_count, a.latest_reserved_sequence,
       a.latest_committed_sequence, a.pending_count, r.provider_reservation_digest,
       c.operation_id AS latest_committed_operation_id,
       c.provider_receipt_digest, c.db_system_id, c.db_timeline, c.required_lsn,
       (a.record_count <> a.latest_reserved_sequence) AS has_sequence_gap
FROM latest_epoch e CROSS JOIN aggregate_head a
LEFT JOIN latest_record r ON true
LEFT JOIN latest_committed c ON true
`

type GetAuthorityFenceHeadRow struct {
	AuthorityEpoch             int64          `json:"authority_epoch"`
	RecordCount                int64          `json:"record_count"`
	LatestReservedSequence     int64          `json:"latest_reserved_sequence"`
	LatestCommittedSequence    int64          `json:"latest_committed_sequence"`
	PendingCount               int64          `json:"pending_count"`
	ProviderReservationDigest  []byte         `json:"provider_reservation_digest"`
	LatestCommittedOperationID uuid.NullUUID  `json:"latest_committed_operation_id"`
	ProviderReceiptDigest      []byte         `json:"provider_receipt_digest"`
	DbSystemID                 pgtype.Numeric `json:"db_system_id"`
	DbTimeline                 pgtype.Int8    `json:"db_timeline"`
	RequiredLsn                interface{}    `json:"required_lsn"`
	HasSequenceGap             bool           `json:"has_sequence_gap"`
}

func (q *Queries) GetAuthorityFenceHead(ctx context.Context) (GetAuthorityFenceHeadRow, error) {
	row := q.db.QueryRow(ctx, getAuthorityFenceHead)
	var i GetAuthorityFenceHeadRow
	err := row.Scan(
		&i.AuthorityEpoch,
		&i.RecordCount,
		&i.LatestReservedSequence,
		&i.LatestCommittedSequence,
		&i.PendingCount,
		&i.ProviderReservationDigest,
		&i.LatestCommittedOperationID,
		&i.ProviderReceiptDigest,
		&i.DbSystemID,
		&i.DbTimeline,
		&i.RequiredLsn,
		&i.HasSequenceGap,
	)
	return i, err
}

const getCommittedNodeCheckpoint = `-- name: GetCommittedNodeCheckpoint :one
SELECT authority_epoch, authority_sequence, provider_receipt_digest
FROM nodecontrol.control_plane_authority_fences
WHERE authority_epoch = $1
  AND provider_status = 'committed' AND visibility_state = 'active'
  AND (scope_kind = 'global_node_trust'
       OR (scope_kind = 'node' AND scope_digest = $2))
ORDER BY authority_sequence DESC
LIMIT 1
`

type GetCommittedNodeCheckpointParams struct {
	AuthorityEpoch  int64  `json:"authority_epoch"`
	NodeScopeDigest []byte `json:"node_scope_digest"`
}

type GetCommittedNodeCheckpointRow struct {
	AuthorityEpoch        int64  `json:"authority_epoch"`
	AuthoritySequence     int64  `json:"authority_sequence"`
	ProviderReceiptDigest []byte `json:"provider_receipt_digest"`
}

func (q *Queries) GetCommittedNodeCheckpoint(ctx context.Context, arg GetCommittedNodeCheckpointParams) (GetCommittedNodeCheckpointRow, error) {
	row := q.db.QueryRow(ctx, getCommittedNodeCheckpoint, arg.AuthorityEpoch, arg.NodeScopeDigest)
	var i GetCommittedNodeCheckpointRow
	err := row.Scan(&i.AuthorityEpoch, &i.AuthoritySequence, &i.ProviderReceiptDigest)
	return i, err
}

const getNodeControlDatabaseIdentity = `-- name: GetNodeControlDatabaseIdentity :one
SELECT system_identifier::numeric(20,0) AS system_id,
       timeline_id::bigint AS timeline,
       pg_current_wal_insert_lsn()::text AS required_lsn
FROM pg_control_system(), pg_control_checkpoint()
`

type GetNodeControlDatabaseIdentityRow struct {
	SystemID    pgtype.Numeric `json:"system_id"`
	Timeline    int64          `json:"timeline"`
	RequiredLsn string         `json:"required_lsn"`
}

func (q *Queries) GetNodeControlDatabaseIdentity(ctx context.Context) (GetNodeControlDatabaseIdentityRow, error) {
	row := q.db.QueryRow(ctx, getNodeControlDatabaseIdentity)
	var i GetNodeControlDatabaseIdentityRow
	err := row.Scan(&i.SystemID, &i.Timeline, &i.RequiredLsn)
	return i, err
}

const insertAuthorityFencePending = `-- name: InsertAuthorityFencePending :execrows
INSERT INTO nodecontrol.control_plane_authority_fences
  (operation_id, effect_kind, scope_kind, authority_epoch, authority_sequence, scope_digest,
   provider_reservation_digest, provider_status, visibility_state, reserved_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'reserved', 'fence_pending', $8)
ON CONFLICT (operation_id) DO NOTHING
`

type InsertAuthorityFencePendingParams struct {
	OperationID               uuid.UUID          `json:"operation_id"`
	EffectKind                string             `json:"effect_kind"`
	ScopeKind                 string             `json:"scope_kind"`
	AuthorityEpoch            int64              `json:"authority_epoch"`
	AuthoritySequence         int64              `json:"authority_sequence"`
	ScopeDigest               []byte             `json:"scope_digest"`
	ProviderReservationDigest []byte             `json:"provider_reservation_digest"`
	ReservedAt                pgtype.Timestamptz `json:"reserved_at"`
}

func (q *Queries) InsertAuthorityFencePending(ctx context.Context, arg InsertAuthorityFencePendingParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAuthorityFencePending,
		arg.OperationID,
		arg.EffectKind,
		arg.ScopeKind,
		arg.AuthorityEpoch,
		arg.AuthoritySequence,
		arg.ScopeDigest,
		arg.ProviderReservationDigest,
		arg.ReservedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPendingAuthorityFences = `-- name: ListPendingAuthorityFences :many
SELECT operation_id, effect_kind, scope_kind, scope_digest, authority_epoch,
       authority_sequence, provider_reservation_digest, effect_digest,
       db_system_id, db_timeline, required_lsn, reserved_at, effect_bound_at
FROM nodecontrol.control_plane_authority_fences
WHERE authority_epoch = $1
  AND provider_status = 'reserved' AND visibility_state = 'fence_pending'
ORDER BY authority_sequence
`

type ListPendingAuthorityFencesRow struct {
	OperationID               uuid.UUID          `json:"operation_id"`
	EffectKind                string             `json:"effect_kind"`
	ScopeKind                 string             `json:"scope_kind"`
	ScopeDigest               []byte             `json:"scope_digest"`
	AuthorityEpoch            int64              `json:"authority_epoch"`
	AuthoritySequence         int64              `json:"authority_sequence"`
	ProviderReservationDigest []byte             `json:"provider_reservation_digest"`
	EffectDigest              []byte             `json:"effect_digest"`
	DbSystemID                pgtype.Numeric     `json:"db_system_id"`
	DbTimeline                pgtype.Int8        `json:"db_timeline"`
	RequiredLsn               interface{}        `json:"required_lsn"`
	ReservedAt                pgtype.Timestamptz `json:"reserved_at"`
	EffectBoundAt             pgtype.Timestamptz `json:"effect_bound_at"`
}

func (q *Queries) ListPendingAuthorityFences(ctx context.Context, authorityEpoch int64) ([]ListPendingAuthorityFencesRow, error) {
	rows, err := q.db.Query(ctx, listPendingAuthorityFences, authorityEpoch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingAuthorityFencesRow{}
	for rows.Next() {
		var i ListPendingAuthorityFencesRow
		if err := rows.Scan(
			&i.OperationID,
			&i.EffectKind,
			&i.ScopeKind,
			&i.ScopeDigest,
			&i.AuthorityEpoch,
			&i.AuthoritySequence,
			&i.ProviderReservationDigest,
			&i.EffectDigest,
			&i.DbSystemID,
			&i.DbTimeline,
			&i.RequiredLsn,
			&i.ReservedAt,
			&i.EffectBoundAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
