// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package store

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const claimOutboxBatch = `-- name: ClaimOutboxBatch :many
WITH candidates AS (
  SELECT candidate.event_id FROM transactional_outbox AS candidate
  WHERE candidate.published_at IS NULL AND candidate.available_at <= $1
    AND (candidate.claimed_until IS NULL OR candidate.claimed_until < $1)
  ORDER BY candidate.occurred_at
  LIMIT $2
  FOR UPDATE OF candidate SKIP LOCKED
)
UPDATE transactional_outbox o
SET claimed_until = $3, attempts = o.attempts + 1
FROM candidates c
WHERE o.event_id = c.event_id
RETURNING o.event_id, o.event_type, o.aggregate_type, o.aggregate_id, o.aggregate_version, o.idempotency_key, o.payload, o.occurred_at, o.available_at, o.claimed_until, o.attempts, o.published_at
`

type ClaimOutboxBatchParams struct {
	AvailableAt  time.Time    `json:"available_at"`
	Limit        int32        `json:"limit"`
	ClaimedUntil sql.NullTime `json:"claimed_until"`
}

func (q *Queries) ClaimOutboxBatch(ctx context.Context, arg ClaimOutboxBatchParams) ([]TransactionalOutbox, error) {
	rows, err := q.db.Query(ctx, claimOutboxBatch, arg.AvailableAt, arg.Limit, arg.ClaimedUntil)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionalOutbox{}
	for rows.Next() {
		var i TransactionalOutbox
		if err := rows.Scan(
			&i.EventID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.AggregateVersion,
			&i.IdempotencyKey,
			&i.Payload,
			&i.OccurredAt,
			&i.AvailableAt,
			&i.ClaimedUntil,
			&i.Attempts,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutboxHealth = `-- name: GetOutboxHealth :one
SELECT count(*)::bigint AS backlog,
       COALESCE(EXTRACT(EPOCH FROM ($1-min(occurred_at))),0)::double precision AS oldest_age_seconds
FROM transactional_outbox WHERE published_at IS NULL
`

type GetOutboxHealthRow struct {
	Backlog          int64   `json:"backlog"`
	OldestAgeSeconds float64 `json:"oldest_age_seconds"`
}

func (q *Queries) GetOutboxHealth(ctx context.Context, occurredAt time.Time) (GetOutboxHealthRow, error) {
	row := q.db.QueryRow(ctx, getOutboxHealth, occurredAt)
	var i GetOutboxHealthRow
	err := row.Scan(&i.Backlog, &i.OldestAgeSeconds)
	return i, err
}

const hasConsumedEvent = `-- name: HasConsumedEvent :one
SELECT EXISTS (
  SELECT 1 FROM consumed_event_ids
  WHERE consumer=$1 AND event_id=$2
)
`

type HasConsumedEventParams struct {
	Consumer string    `json:"consumer"`
	EventID  uuid.UUID `json:"event_id"`
}

func (q *Queries) HasConsumedEvent(ctx context.Context, arg HasConsumedEventParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasConsumedEvent, arg.Consumer, arg.EventID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO transactional_outbox
  (event_id,event_type,aggregate_type,aggregate_id,aggregate_version,
   idempotency_key,payload,occurred_at,available_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
`

type InsertOutboxEventParams struct {
	EventID          uuid.UUID `json:"event_id"`
	EventType        string    `json:"event_type"`
	AggregateType    string    `json:"aggregate_type"`
	AggregateID      uuid.UUID `json:"aggregate_id"`
	AggregateVersion int64     `json:"aggregate_version"`
	IdempotencyKey   string    `json:"idempotency_key"`
	Payload          []byte    `json:"payload"`
	OccurredAt       time.Time `json:"occurred_at"`
	AvailableAt      time.Time `json:"available_at"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.EventID,
		arg.EventType,
		arg.AggregateType,
		arg.AggregateID,
		arg.AggregateVersion,
		arg.IdempotencyKey,
		arg.Payload,
		arg.OccurredAt,
		arg.AvailableAt,
	)
	return err
}

const markOutboxPublished = `-- name: MarkOutboxPublished :execrows
UPDATE transactional_outbox SET published_at = $2, claimed_until = NULL
WHERE event_id = $1 AND published_at IS NULL
`

type MarkOutboxPublishedParams struct {
	EventID     uuid.UUID    `json:"event_id"`
	PublishedAt sql.NullTime `json:"published_at"`
}

func (q *Queries) MarkOutboxPublished(ctx context.Context, arg MarkOutboxPublishedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxPublished, arg.EventID, arg.PublishedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneConsumedEvents = `-- name: PruneConsumedEvents :execrows
DELETE FROM consumed_event_ids WHERE expires_at < $1
`

func (q *Queries) PruneConsumedEvents(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, pruneConsumedEvents, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordConsumedEvent = `-- name: RecordConsumedEvent :execrows
INSERT INTO consumed_event_ids (consumer, event_id, consumed_at, expires_at)
VALUES ($1,$2,$3,$4)
ON CONFLICT DO NOTHING
`

type RecordConsumedEventParams struct {
	Consumer   string    `json:"consumer"`
	EventID    uuid.UUID `json:"event_id"`
	ConsumedAt time.Time `json:"consumed_at"`
	ExpiresAt  time.Time `json:"expires_at"`
}

func (q *Queries) RecordConsumedEvent(ctx context.Context, arg RecordConsumedEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordConsumedEvent,
		arg.Consumer,
		arg.EventID,
		arg.ConsumedAt,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseOutboxClaim = `-- name: ReleaseOutboxClaim :execrows
UPDATE transactional_outbox
SET claimed_until=NULL, available_at=$2
WHERE event_id=$1 AND published_at IS NULL
`

type ReleaseOutboxClaimParams struct {
	EventID     uuid.UUID `json:"event_id"`
	AvailableAt time.Time `json:"available_at"`
}

func (q *Queries) ReleaseOutboxClaim(ctx context.Context, arg ReleaseOutboxClaimParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseOutboxClaim, arg.EventID, arg.AvailableAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
