// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"encoding/json"
)

type Querier interface {
	GetSystemMetadata(ctx context.Context, key string) (json.RawMessage, error)
	PutSystemMetadata(ctx context.Context, arg PutSystemMetadataParams) error
}

var _ Querier = (*Queries)(nil)
