// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system_metadata.sql

package store

import (
	"context"
	"encoding/json"
)

const getSystemMetadata = `-- name: GetSystemMetadata :one
SELECT value
FROM system_metadata
WHERE key = $1
`

func (q *Queries) GetSystemMetadata(ctx context.Context, key string) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getSystemMetadata, key)
	var value json.RawMessage
	err := row.Scan(&value)
	return value, err
}

const putSystemMetadata = `-- name: PutSystemMetadata :exec
INSERT INTO system_metadata (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value, updated_at = now()
`

type PutSystemMetadataParams struct {
	Key   string          `json:"key"`
	Value json.RawMessage `json:"value"`
}

func (q *Queries) PutSystemMetadata(ctx context.Context, arg PutSystemMetadataParams) error {
	_, err := q.db.Exec(ctx, putSystemMetadata, arg.Key, arg.Value)
	return err
}
