// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trust.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getBundleByLocatorHash = `-- name: GetBundleByLocatorHash :one
SELECT id, authorization_id, bundle_version, locator_hash, locator_ciphertext, locator_key_version, envelope, envelope_sha256, signer_key_id, issued_at, not_before, expires_at FROM trust.bundle_issuances
WHERE locator_hash = $1 AND expires_at >= $2
`

type GetBundleByLocatorHashParams struct {
	LocatorHash []byte    `json:"locator_hash"`
	ExpiresAt   time.Time `json:"expires_at"`
}

func (q *Queries) GetBundleByLocatorHash(ctx context.Context, arg GetBundleByLocatorHashParams) (TrustBundleIssuance, error) {
	row := q.db.QueryRow(ctx, getBundleByLocatorHash, arg.LocatorHash, arg.ExpiresAt)
	var i TrustBundleIssuance
	err := row.Scan(
		&i.ID,
		&i.AuthorizationID,
		&i.BundleVersion,
		&i.LocatorHash,
		&i.LocatorCiphertext,
		&i.LocatorKeyVersion,
		&i.Envelope,
		&i.EnvelopeSha256,
		&i.SignerKeyID,
		&i.IssuedAt,
		&i.NotBefore,
		&i.ExpiresAt,
	)
	return i, err
}

const getBundleIssuance = `-- name: GetBundleIssuance :one
SELECT id, authorization_id, bundle_version, locator_hash, locator_ciphertext, locator_key_version, envelope, envelope_sha256, signer_key_id, issued_at, not_before, expires_at FROM trust.bundle_issuances WHERE id=$1
`

func (q *Queries) GetBundleIssuance(ctx context.Context, id uuid.UUID) (TrustBundleIssuance, error) {
	row := q.db.QueryRow(ctx, getBundleIssuance, id)
	var i TrustBundleIssuance
	err := row.Scan(
		&i.ID,
		&i.AuthorizationID,
		&i.BundleVersion,
		&i.LocatorHash,
		&i.LocatorCiphertext,
		&i.LocatorKeyVersion,
		&i.Envelope,
		&i.EnvelopeSha256,
		&i.SignerKeyID,
		&i.IssuedAt,
		&i.NotBefore,
		&i.ExpiresAt,
	)
	return i, err
}

const getHighestBundleVersion = `-- name: GetHighestBundleVersion :one
SELECT highest_issued FROM trust.highest_bundle_versions WHERE authorization_id=$1
`

func (q *Queries) GetHighestBundleVersion(ctx context.Context, authorizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getHighestBundleVersion, authorizationID)
	var highest_issued int64
	err := row.Scan(&highest_issued)
	return highest_issued, err
}

const getLatestBundleIssuance = `-- name: GetLatestBundleIssuance :one
SELECT id, authorization_id, bundle_version, locator_hash, locator_ciphertext, locator_key_version, envelope, envelope_sha256, signer_key_id, issued_at, not_before, expires_at FROM trust.bundle_issuances
WHERE authorization_id=$1
ORDER BY bundle_version DESC
LIMIT 1
`

func (q *Queries) GetLatestBundleIssuance(ctx context.Context, authorizationID uuid.UUID) (TrustBundleIssuance, error) {
	row := q.db.QueryRow(ctx, getLatestBundleIssuance, authorizationID)
	var i TrustBundleIssuance
	err := row.Scan(
		&i.ID,
		&i.AuthorizationID,
		&i.BundleVersion,
		&i.LocatorHash,
		&i.LocatorCiphertext,
		&i.LocatorKeyVersion,
		&i.Envelope,
		&i.EnvelopeSha256,
		&i.SignerKeyID,
		&i.IssuedAt,
		&i.NotBefore,
		&i.ExpiresAt,
	)
	return i, err
}

const insertBundleAcknowledgement = `-- name: InsertBundleAcknowledgement :exec
INSERT INTO trust.bundle_acknowledgements
  (bundle_id, authorization_id, bundle_version, acknowledged_at)
VALUES ($1,$2,$3,$4)
ON CONFLICT (bundle_id, authorization_id) DO NOTHING
`

type InsertBundleAcknowledgementParams struct {
	BundleID        uuid.UUID `json:"bundle_id"`
	AuthorizationID uuid.UUID `json:"authorization_id"`
	BundleVersion   int64     `json:"bundle_version"`
	AcknowledgedAt  time.Time `json:"acknowledged_at"`
}

func (q *Queries) InsertBundleAcknowledgement(ctx context.Context, arg InsertBundleAcknowledgementParams) error {
	_, err := q.db.Exec(ctx, insertBundleAcknowledgement,
		arg.BundleID,
		arg.AuthorizationID,
		arg.BundleVersion,
		arg.AcknowledgedAt,
	)
	return err
}

const insertBundleIssuance = `-- name: InsertBundleIssuance :exec
INSERT INTO trust.bundle_issuances
  (id, authorization_id, bundle_version, locator_hash, locator_ciphertext,
   locator_key_version, envelope, envelope_sha256, signer_key_id,
   issued_at, not_before, expires_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
`

type InsertBundleIssuanceParams struct {
	ID                uuid.UUID `json:"id"`
	AuthorizationID   uuid.UUID `json:"authorization_id"`
	BundleVersion     int64     `json:"bundle_version"`
	LocatorHash       []byte    `json:"locator_hash"`
	LocatorCiphertext []byte    `json:"locator_ciphertext"`
	LocatorKeyVersion int32     `json:"locator_key_version"`
	Envelope          []byte    `json:"envelope"`
	EnvelopeSha256    []byte    `json:"envelope_sha256"`
	SignerKeyID       string    `json:"signer_key_id"`
	IssuedAt          time.Time `json:"issued_at"`
	NotBefore         time.Time `json:"not_before"`
	ExpiresAt         time.Time `json:"expires_at"`
}

func (q *Queries) InsertBundleIssuance(ctx context.Context, arg InsertBundleIssuanceParams) error {
	_, err := q.db.Exec(ctx, insertBundleIssuance,
		arg.ID,
		arg.AuthorizationID,
		arg.BundleVersion,
		arg.LocatorHash,
		arg.LocatorCiphertext,
		arg.LocatorKeyVersion,
		arg.Envelope,
		arg.EnvelopeSha256,
		arg.SignerKeyID,
		arg.IssuedAt,
		arg.NotBefore,
		arg.ExpiresAt,
	)
	return err
}

const insertSigningKeyMetadata = `-- name: InsertSigningKeyMetadata :exec
INSERT INTO trust.signing_key_metadata
  (key_id, root_metadata_version, algorithm, public_key, state, not_before, not_after)
VALUES ($1,$2,'Ed25519',$3,$4,$5,$6)
`

type InsertSigningKeyMetadataParams struct {
	KeyID               string    `json:"key_id"`
	RootMetadataVersion int64     `json:"root_metadata_version"`
	PublicKey           []byte    `json:"public_key"`
	State               string    `json:"state"`
	NotBefore           time.Time `json:"not_before"`
	NotAfter            time.Time `json:"not_after"`
}

func (q *Queries) InsertSigningKeyMetadata(ctx context.Context, arg InsertSigningKeyMetadataParams) error {
	_, err := q.db.Exec(ctx, insertSigningKeyMetadata,
		arg.KeyID,
		arg.RootMetadataVersion,
		arg.PublicKey,
		arg.State,
		arg.NotBefore,
		arg.NotAfter,
	)
	return err
}

const insertTrustRootMetadata = `-- name: InsertTrustRootMetadata :exec
INSERT INTO trust.trust_root_metadata
  (version, canonical_payload, signature, valid_from, valid_until, created_at)
VALUES ($1,$2,$3,$4,$5,$6)
`

type InsertTrustRootMetadataParams struct {
	Version          int64     `json:"version"`
	CanonicalPayload []byte    `json:"canonical_payload"`
	Signature        []byte    `json:"signature"`
	ValidFrom        time.Time `json:"valid_from"`
	ValidUntil       time.Time `json:"valid_until"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) InsertTrustRootMetadata(ctx context.Context, arg InsertTrustRootMetadataParams) error {
	_, err := q.db.Exec(ctx, insertTrustRootMetadata,
		arg.Version,
		arg.CanonicalPayload,
		arg.Signature,
		arg.ValidFrom,
		arg.ValidUntil,
		arg.CreatedAt,
	)
	return err
}

const listSigningKeysForMetadata = `-- name: ListSigningKeysForMetadata :many
SELECT key_id, root_metadata_version, algorithm, public_key, state, not_before, not_after FROM trust.signing_key_metadata
WHERE root_metadata_version=$1 ORDER BY key_id
`

func (q *Queries) ListSigningKeysForMetadata(ctx context.Context, rootMetadataVersion int64) ([]TrustSigningKeyMetadatum, error) {
	rows, err := q.db.Query(ctx, listSigningKeysForMetadata, rootMetadataVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrustSigningKeyMetadatum{}
	for rows.Next() {
		var i TrustSigningKeyMetadatum
		if err := rows.Scan(
			&i.KeyID,
			&i.RootMetadataVersion,
			&i.Algorithm,
			&i.PublicKey,
			&i.State,
			&i.NotBefore,
			&i.NotAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrustRootMetadata = `-- name: ListTrustRootMetadata :many
SELECT version, canonical_payload, signature, valid_from, valid_until, created_at FROM trust.trust_root_metadata ORDER BY version
`

func (q *Queries) ListTrustRootMetadata(ctx context.Context) ([]TrustTrustRootMetadatum, error) {
	rows, err := q.db.Query(ctx, listTrustRootMetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrustTrustRootMetadatum{}
	for rows.Next() {
		var i TrustTrustRootMetadatum
		if err := rows.Scan(
			&i.Version,
			&i.CanonicalPayload,
			&i.Signature,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextBundleVersion = `-- name: NextBundleVersion :one
INSERT INTO trust.highest_bundle_versions (authorization_id, highest_issued, updated_at)
VALUES ($1, 1, $2)
ON CONFLICT (authorization_id) DO UPDATE
SET highest_issued = trust.highest_bundle_versions.highest_issued + 1,
    updated_at = EXCLUDED.updated_at
RETURNING highest_issued
`

type NextBundleVersionParams struct {
	AuthorizationID uuid.UUID `json:"authorization_id"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) NextBundleVersion(ctx context.Context, arg NextBundleVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, nextBundleVersion, arg.AuthorizationID, arg.UpdatedAt)
	var highest_issued int64
	err := row.Scan(&highest_issued)
	return highest_issued, err
}
